### ISSUE TITLE
Do not create cache directory if cache is disabled

### ISSUE THREAD

**Issue by dgcampea** [jcorporation/myMPD#890] opened 2022-11-16 15:57 UTC
myMPD version: 10.1.1

**Describe the bug**

When launching _mympd_ with an empty config directory (the time it will honor env vars), _mympd_ fails to launch if it can't create the cache directory, even when with the environment variable `MYMPD_COVERCACHE_KEEP_DAY` set to `0`.

**To Reproduce**
Run:
```
$ MYMPD_COVERCACHE_KEEP_DAY=0 mympd -u mympd -w <X> -a <Y>
```
Where `X/config` is either empty or does not exist.

**Debug logs (please attach if it can be useful)**

- myMPD log
```
2022-11-16 16:47:16 NOTICE   mympd     Work dir: "/var/lib/mympd"
2022-11-16 16:47:16 NOTICE   mympd     Config dir: "/var/lib/mympd/config" created
2022-11-16 16:47:16 ERROR    mympd     Cache dir: creating "/var/cache/mympd" failed
2022-11-16 16:47:16 ERROR    mympd     No such file or directory
2022-11-16 16:47:16 NOTICE   mympd     Work dir: "/var/lib/mympd"
2022-11-16 16:47:16 NOTICE   mympd     Config dir: "/var/lib/mympd/config"
2022-11-16 16:47:16 ERROR    mympd     Cache dir: creating "/var/cache/mympd" failed
2022-11-16 16:47:16 ERROR    mympd     No such file or directory
```

**Comment by dgcampea** [comment] 2022-11-16 17:11
A similar issue occurs with _HTTPS_ support, it generates a cert+key even when disabled through environment variable.

**Comment by jcorporation** [comment] 2022-11-16 20:39
> A similar issue occurs with HTTPS support, it generates a cert+key even when disabled through environment variable.

I can not reproduce this. Please remove the config directory and all files from `/var/lib/mympd/ssl` and start in debug mode.

**Comment by jcorporation** [comment] 2022-11-16 21:40
The cache directory is not only used for the covercache. The webradiodb feature uses also the cache directory.

**Comment by dgcampea** [comment] 2022-11-17 15:05
> The cache directory is not only used for the covercache. The webradiodb feature uses also the cache directory.

Thanks, I didn't know about this. I was under the impression that the cache was only used for cover caching.

About the webradiodb, how do you use it with mympd? (First time I'm hearing about it)
Is it possible to make it an optional feature in case the user doesn't intend to use it?

Right now mympd will refuse to work if it isn't able to create its cache directory which makes it a bit tougher for space constrained systems. This could be downgraded to a non-fatal error or be a configurable option.

**Comment by dgcampea** [comment] 2022-11-17 15:09
> I can not reproduce this. Please remove the config directory and all files from `/var/lib/mympd/ssl` and start in debug mode.

My bad, upon further investigation, it doesn't do this, rather the logs seem to suggest that ssl keys were created.
I presume this issue is fixed with the recent b5b9137d69bfc3f374a522951fc2921c0ad5c525 commit.

**Comment by dgcampea** [comment] 2022-11-17 17:27
Strange issue. While digging further on this `/var/cache` issue, I found out that:

1. If the parent directory where mympd wants to create the cache directory doesn't exist, it ~will terminate~  keeps trying  and does not advance further. (scenario: args `-w /var/cache/mympd` but `/var/cache` does not exist)
```
2022-11-17 18:04:40 NOTICE   mympd     Work dir: "/var/lib/mympd"
2022-11-17 18:04:40 NOTICE   mympd     Config dir: "/var/lib/mympd/config" created
2022-11-17 18:04:40 ERROR    mympd     Cache dir: creating "/var/cache/mympd" failed
2022-11-17 18:04:40 ERROR    mympd     No such file or directory
2022-11-17 18:04:40 NOTICE   mympd     Work dir: "/var/lib/mympd"
2022-11-17 18:04:40 NOTICE   mympd     Config dir: "/var/lib/mympd/config"
2022-11-17 18:04:40 ERROR    mympd     Cache dir: creating "/var/cache/mympd" failed
2022-11-17 18:04:40 ERROR    mympd     No such file or directory
2022-11-17 18:04:40 NOTICE   mympd     Work dir: "/var/lib/mympd"
2022-11-17 18:04:40 NOTICE   mympd     Config dir: "/var/lib/mympd/config"
2022-11-17 18:04:40 ERROR    mympd     Cache dir: creating "/var/cache/mympd" failed
2022-11-17 18:04:40 ERROR    mympd     No such file or directory
2022-11-17 18:04:40 NOTICE   mympd     Work dir: "/var/lib/mympd"
2022-11-17 18:04:40 NOTICE   mympd     Config dir: "/var/lib/mympd/config"
2022-11-17 18:04:40 ERROR    mympd     Cache dir: creating "/var/cache/mympd" failed
2022-11-17 18:04:40 ERROR    mympd     No such file or directory
2022-11-17 18:04:40 NOTICE   mympd     Work dir: "/var/lib/mympd"
2022-11-17 18:04:40 NOTICE   mympd     Config dir: "/var/lib/mympd/config"
2022-11-17 18:04:40 ERROR    mympd     Cache dir: creating "/var/cache/mympd" failed
2022-11-17 18:04:40 ERROR    mympd     No such file or directory
2022-11-17 18:04:40 NOTICE   mympd     Work dir: "/var/lib/mympd"
2022-11-17 18:04:40 NOTICE   mympd     Config dir: "/var/lib/mympd/config"
2022-11-17 18:04:40 ERROR    mympd     Cache dir: creating "/var/cache/mympd" failed
2022-11-17 18:04:40 ERROR    mympd     No such file or directory
2022-11-17 18:04:40 NOTICE   mympd     Work dir: "/var/lib/mympd"
2022-11-17 18:04:40 NOTICE   mympd     Config dir: "/var/lib/mympd/config"
2022-11-17 18:04:40 ERROR    mympd     Cache dir: creating "/var/cache/mympd" failed
2022-11-17 18:04:40 ERROR    mympd     No such file or directory
```

2. If mympd fails to notice the directory initially but ends up succeeding in a subsequent retry, it ignores __env vars__
```
2022-11-17 17:29:24 NOTICE   mympd     Work dir: "/var/lib/mympd"                                                                 
2022-11-17 17:29:24 NOTICE   mympd     Config dir: "/var/lib/mympd/config" created
2022-11-17 17:29:24 ERROR    mympd     Cache dir: creating "/var/cache/mympd" failed
2022-11-17 17:29:24 ERROR    mympd     No such file or directory
2022-11-17 17:29:24 NOTICE   mympd     Work dir: "/var/lib/mympd"
2022-11-17 17:29:24 NOTICE   mympd     Config dir: "/var/lib/mympd/config"
2022-11-17 17:29:24 NOTICE   mympd     Cache dir: "/var/cache/mympd" created
2022-11-17 17:29:24 NOTICE   mympd     Setting loglevel to DEBUG
2022-11-17 17:29:24 NOTICE   mympd     Starting myMPD 10.1.1
2022-11-17 17:29:24 INFO     mympd     Libmympdclient 1.0.15 based on libmpdclient 2.21.0
2022-11-17 17:29:24 INFO     mympd     Mongoose 7.8
2022-11-17 17:29:24 INFO     mympd     Lua 5.3.5
2022-11-17 17:29:24 INFO     mympd     Libid3tag 0.15.1 (beta)
2022-11-17 17:29:24 INFO     mympd     FLAC 11.0.3
2022-11-17 17:29:24 INFO     mympd     OpenSSL 1.1.1l  24 Aug 2021
2022-11-17 17:29:24 WARN     mympd     No valid nameserver found
2022-11-17 17:29:24 DEBUG    mympd     Setting dns server to udp://8.8.8.8:53
2022-11-17 17:29:24 NOTICE   mympd     Listening on http://0.0.0.0:80
2022-11-17 17:29:24 NOTICE   mympd     Listening on https://0.0.0.0:443
2022-11-17 17:29:24 NOTICE   mympd     Serving files from "/ro/mympd-10.1.1/var/empty"
2022-11-17 17:29:24 NOTICE   mympd     Droping privileges to user "mympd"
2022-11-17 17:29:24 NOTICE   mympd     SSL cert dir: "/var/lib/mympd/ssl" created
2022-11-17 17:29:24 NOTICE   mympd     Creating self signed ca certificate
2022-11-17 17:29:24 NOTICE   mympd     Creating server certificate
2022-11-17 17:29:24 DEBUG    mympd     Adding DNS:localhost to SAN
2022-11-17 17:29:24 DEBUG    mympd     Adding DNS:<scrubbed> to SAN
2022-11-17 17:29:24 DEBUG    mympd     Adding DNS:localhost to SAN
2022-11-17 17:29:24 DEBUG    mympd     Adding IP:127.0.0.1 to SAN
2022-11-17 17:29:24 DEBUG    mympd     Adding IP:<scrubbed> to SAN
2022-11-17 17:29:24 DEBUG    mympd     Adding IP:::1 to SAN
2022-11-17 17:29:24 DEBUG    mympd     Adding IP:<scrubbed> to SAN
2022-11-17 17:29:24 NOTICE   mympd     Set server certificate san to: DNS:localhost,DNS:ip6-localhost,DNS:ip6-loopback,DNS:<scrubbed>,DNS:localhost,IP:127.0.0.1,IP:<scrubbed>,IP:::1,IP:<scrubbed>
2022-11-17 17:29:24 NOTICE   mympd     Empty dir: "/var/lib/mympd/empty" created
2022-11-17 17:29:24 NOTICE   mympd     Pics dir: "/var/lib/mympd/pics" created
2022-11-17 17:29:24 NOTICE   mympd     Backgrounds dir: "/var/lib/mympd/pics/backgrounds" created
2022-11-17 17:29:24 NOTICE   mympd     Thumbnails dir: "/var/lib/mympd/pics/thumbs" created
2022-11-17 17:29:24 NOTICE   mympd     Scripts dir: "/var/lib/mympd/scripts" created
2022-11-17 17:29:24 NOTICE   mympd     Smartpls dir: "/var/lib/mympd/smartpls" created
2022-11-17 17:29:24 NOTICE   mympd     State dir: "/var/lib/mympd/state" created
2022-11-17 17:29:24 NOTICE   mympd     Default partition dir: "/var/lib/mympd/state/default" created
2022-11-17 17:29:24 NOTICE   mympd     Webradio dir: "/var/lib/mympd/webradios" created
2022-11-17 17:29:24 NOTICE   mympd     Covercache dir: "/var/cache/mympd/covercache" created
2022-11-17 17:29:24 NOTICE   mympd     Webradiodb cache dir: "/var/cache/mympd/webradiodb" created
2022-11-17 17:29:24 NOTICE   mympd     Starting mympd api thread
2022-11-17 17:29:24 NOTICE   mympd     Starting webserver thread
2022-11-17 17:29:24 NOTICE   mympd     myMPD is ready
2022-11-17 17:29:24 DEBUG    webserver Using certificate: /var/lib/mympd/ssl/server.pem
2022-11-17 17:29:24 DEBUG    webserver Using private key: /var/lib/mympd/ssl/server.key
2022-11-17 17:29:24 NOTICE   mympdapi  Reading global states
2022-11-17 17:29:24 INFO     webserver Connection 3 closed
2022-11-17 17:29:24 INFO     webserver Redirecting to https://localhost
2022-11-17 17:29:24 DEBUG    webserver Sending 301 Moved Permanently "https://localhost" to 4
2022-11-17 17:29:24 INFO     webserver Connection 4 closed
```
Note: I'm not sure myself what's exactly happening here, I suspect it's a timing issue (`/var/cache` was created shortly before launching mympd)
Note 2: The _DEBUG_ messages seem to have trouble dealing with a hostname that contains dashes. (notice `loopback` mentioned twice but the _NOTICE_ line contains `ip6-localhost` and `localhost`)
Note 2.1: There's a stray `DNS:ip6-loopback` logged in _NOTICE_ that is not mentioned in the preceeding _DEBUG_ lines.

3. Non degenerate case (`/var/cache` present for a while before launching `mympd`)
```
2022-11-17 16:38:04 NOTICE   mympd     Work dir: "/var/lib/mympd"
2022-11-17 16:38:04 NOTICE   mympd     Config dir: "/var/lib/mympd/config" created
2022-11-17 16:38:04 NOTICE   mympd     Cache dir: "/var/cache/mympd" created
2022-11-17 16:38:04 NOTICE   mympd     Setting loglevel to DEBUG
2022-11-17 16:38:04 NOTICE   mympd     Starting myMPD 10.1.1
2022-11-17 16:38:04 INFO     mympd     Libmympdclient 1.0.15 based on libmpdclient 2.21.0
2022-11-17 16:38:04 INFO     mympd     Mongoose 7.8
2022-11-17 16:38:04 INFO     mympd     Lua 5.3.5
2022-11-17 16:38:04 INFO     mympd     Libid3tag 0.15.1 (beta)
2022-11-17 16:38:04 INFO     mympd     FLAC 11.0.3
2022-11-17 16:38:04 INFO     mympd     OpenSSL 1.1.1l  24 Aug 2021
2022-11-17 16:38:04 DEBUG    mympd     Setting dns server to udp://10.0.2.3:53
2022-11-17 16:38:04 NOTICE   mympd     Listening on http://[::]:80
2022-11-17 16:38:04 NOTICE   mympd     Serving files from "/ro/10.1.1/var/empty"
2022-11-17 16:38:04 NOTICE   mympd     Droping privileges to user "mympd"
2022-11-17 16:38:04 NOTICE   mympd     Empty dir: "/var/lib/mympd/empty" created
2022-11-17 16:38:04 NOTICE   mympd     Pics dir: "/var/lib/mympd/pics" created
2022-11-17 16:38:04 NOTICE   mympd     Backgrounds dir: "/var/lib/mympd/pics/backgrounds" created
2022-11-17 16:38:04 NOTICE   mympd     Thumbnails dir: "/var/lib/mympd/pics/thumbs" created
2022-11-17 16:38:04 NOTICE   mympd     Scripts dir: "/var/lib/mympd/scripts" created
2022-11-17 16:38:04 NOTICE   mympd     Smartpls dir: "/var/lib/mympd/smartpls" created
2022-11-17 16:38:04 NOTICE   mympd     State dir: "/var/lib/mympd/state" created
2022-11-17 16:38:04 NOTICE   mympd     Default partition dir: "/var/lib/mympd/state/default" created
2022-11-17 16:38:04 NOTICE   mympd     Webradio dir: "/var/lib/mympd/webradios" created
2022-11-17 16:38:04 NOTICE   mympd     Covercache dir: "/var/cache/mympd/covercache" created
2022-11-17 16:38:04 NOTICE   mympd     Webradiodb cache dir: "/var/cache/mympd/webradiodb" created
2022-11-17 16:38:04 NOTICE   mympd     Starting mympd api thread
2022-11-17 16:38:04 NOTICE   mympd     Starting webserver thread
2022-11-17 16:38:04 NOTICE   mympd     myMPD is ready
2022-11-17 16:38:04 DEBUG    webserver Using certificate: /var/lib/mympd/ssl/server.pem
2022-11-17 16:38:04 DEBUG    webserver Using private key: /var/lib/mympd/ssl/server.key
2022-11-17 16:38:04 NOTICE   mympdapi  Starting myMPD autoconfiguration
2022-11-17 16:38:04 NOTICE   mympdapi  Reading environment
2022-11-17 16:38:04 DEBUG    mympdapi  Environment variable "MPD_HOST" not set
2022-11-17 16:38:04 DEBUG    mympdapi  Environment variable "MPD_PORT" not set
2022-11-17 16:38:04 DEBUG    mympdapi  Environment variable "MPD_TIMEOUT" not set
2022-11-17 16:38:04 DEBUG    mympdapi  Environment variable "XDG_RUNTIME_DIR" not set
2022-11-17 16:38:04 DEBUG    mympdapi  MPD connection: No such file or directory
2022-11-17 16:38:04 DEBUG    mympdapi  MPD connection: Connection refused
2022-11-17 16:38:04 DEBUG    mympdapi  MPD connection: No such file or directory
2022-11-17 16:38:04 WARN     mympdapi  MPD autoconfiguration failed
2022-11-17 16:38:04 NOTICE   mympdapi  Setting mpd host to "localhost"
2022-11-17 16:38:04 NOTICE   mympdapi  Setting mpd port to "6600"
2022-11-17 16:38:04 NOTICE   mympdapi  Reading global states
2022-11-17 16:38:04 DEBUG    mympdapi  Read 10 bytes from file
2022-11-17 16:38:04 DEBUG    mympdapi  State smartpls_prefix: myMPDsmart
2022-11-17 16:38:04 NOTICE   mympdapi  "default": Reading partition states from directory "/var/lib/mympd/state/default"
2022-11-17 16:38:04 DEBUG    mympdapi  Can not open file "/var/lib/mympd/state/home_list"
2022-11-17 16:38:04 DEBUG    mympdapi  Can not open file "/var/lib/mympd/state/timer_list"
2022-11-17 16:38:04 DEBUG    mympdapi  Can not open file "/var/lib/mympd/state/trigger_list"
2022-11-17 16:38:04 DEBUG    mympdapi  "!all!": Trigger event: mympd_start (-2)
2022-11-17 16:38:04 INFO     mympdapi  Creating mpd connection for partition "default"
2022-11-17 16:38:04 NOTICE   mympdapi  "default": Connecting to "localhost:6600"
2022-11-17 16:38:04 ERROR    mympdapi  "default": Connection: Connection refused
2022-11-17 16:38:04 DEBUG    mympdapi  Push websocket notify to queue: "{"jsonrpc":"2.0","method":"notify","params":{"facility":"mpd","severity":"error","message":"MPD connection error: %{error}","data":{"error":"Connection refused"}}}"
```

**Comment by jcorporation** [comment] 2022-11-17 20:12
> Note 2: The DEBUG messages seem to have trouble dealing with a hostname that contains dashes. (notice loopback mentioned twice but the NOTICE line contains ip6-localhost and localhost)
Note 2.1: There's a stray DNS:ip6-loopback logged in NOTICE that is not mentioned in the preceeding DEBUG lines.

Logging function is working correctly, but myMPD does not log the `ip6-localhost` and `ip6-loopback` addition to san. One of your ips are resolving to `localhost` and myMPD does not filter out the duplicate. This should be improved.

**Comment by jcorporation** [comment] 2022-11-17 20:45
First and second log: myMPD is restarted by another process continuously. myMPD terminates if it can not create the directory. 

> If mympd fails to notice the directory initially but ends up succeeding in a subsequent retry, it ignores env vars

myMPD has created the `config` directory in the first try and in the second try the directory exists already and therefor the env variables are ignores. All works as designed.

**Comment by dgcampea** [comment] 2022-11-17 20:50
> myMPD has created the `config` directory in the first try and in the second try the directory exists already and therefor the env variables are ignores. All works as designed.

That's not the case. Although in the first run it created the config directory, it still hasn't read the env variables since it terminates early due to `cache` dir failure.
In the second log, SSL was disabled through env vars but since it never wrote any of the variables to the `config` dir, you can see that on the second launch it's attempting to force SSL by redirecting with 301.

**Comment by jcorporation** [comment] 2022-11-17 21:04
>About the webradiodb, how do you use it with mympd? (First time I'm hearing about it)
Is it possible to make it an optional feature in case the user doesn't intend to use it?

Browse -> Select view -> Webradios -> Browse WebradioDB

This feature adds hardly no overhead if the user does not use it.

>Right now mympd will refuse to work if it isn't able to create its cache directory which makes it a bit tougher for space constrained systems. This could be downgraded to a non-fatal error or be a configurable option.

This is intended and will not change. I do not want add all the codepaths to myMPD to make this possible. There are only some directories created and this does not excessively bloat any system.

**Comment by jcorporation** [comment] 2022-11-17 21:34
> That's not the case. Although in the first run it created the config directory, it still hasn't read the env variables since it terminates early due to `cache` dir failure. In the second log, SSL was disabled through env vars but since it never wrote any of the variables to the `config` dir, you can see that on the second launch it's attempting to force SSL by redirecting with 301.

Right, fix could be to create the cache directory before the config directory.

**Closed** 2022-11-19 07:19 UTC
Labels: invalid
