### ISSUE TITLE
Bug in theme selection

### ISSUE THREAD

**Issue by DoDiesis** [jcorporation/myMPD#407] opened 2021-01-16 10:17 UTC
myMPD version: 6.10.0

When I change the selected theme in the Appearance page, the background colour always gets set to black, whenever theme you select.
Steps to reproduce the behaviour:
1. Go to Settings/Appearance and change the Theme

Furthermore a warning about a JavaScript error happens:
![image](https://user-images.githubusercontent.com/76726999/104809223-f8eaca80-57eb-11eb-98a0-18ed5f72d757.png)
It reads:
TypeError: document .getElementByld(...) is null
(https://127.0.0.1/js/combined.js: 257)

**Comment by jcorporation** [comment] 2021-01-16 14:49
The javascript bug is already fixed in the v6.11.0 branch. The background color is reset to default values if you change the theme. The bug is caused by the new color picker input that does not accept shortcut rgb values. This is now fixed in the v6.11.0 branch.

**Closed by jcorporation** 2021-01-16 14:49 UTC
Labels: bug
