### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by edhelas** [jcorporation/myMPD#810] opened 2022-08-14 14:29 UTC
myMPD version: 9.5.0

![image](https://user-images.githubusercontent.com/3726886/184541581-9cbbe1f4-d3de-4373-80b3-25d3563648f4.png)

![image](https://user-images.githubusercontent.com/3726886/184541631-600beda2-931e-47c3-8628-a01e287799a4.png)

It seems that the translations files have a faulty path

    https://server.tld/mympdassets/i18n/en-US.json

MyMPD is deployed under the `/mympd` directory and it seems to miss the / just after.

**Comment by edhelas** [comment] 2022-08-14 14:44
From what I see it's only links that are part of the ServiceWorker.

![image](https://user-images.githubusercontent.com/3726886/184542186-16337546-d02b-477b-b0c0-ec5c552cb1a1.png)

**Comment by jcorporation** [comment] 2022-08-14 15:27
Duplicate of #808

**Closed by jcorporation** 2022-08-14 15:28 UTC
Labels: duplicate
