### ISSUE TITLE
cannot open the webUI

### ISSUE THREAD

**Issue by sandbox404** [jcorporation/myMPD#1264] opened 2024-05-02 17:40 UTC
myMPD version: 15.0.0

**Describe the bug**

I have some connection issue on Safari on mympd 14.1.1 (just works good on windows PC using Chrome) so I upgrade mympd immediately. But after upgrade, I cannot open the webUI.

**To Reproduce**

1. apt install ./mympd_15.0.0-1_arm64.deb
2. sudo systemctl start mympd.service
3. open the browser from PC or iOS devices then open the webUI IP address

**Expected behavior**

**Screenshots**

**Server platform (please complete the following information):**
 - OS: Raspberry Pi OS
 - OS version 11
 - Platform: arm64
 - MPD version: 0.23.15

**Client platform (please complete the following information):**
 - Device: iPhone 8, iPhone 13 Pro, PC
 - OS: iOS 16.7.2, iOS 15.5, windows 10
 - Browser: Safari, Safari, Chrome
 - Browser version: Chrome 124.0.6367.118

**Debug logs (please attach if it can be useful)**

May 02 18:28:39 mpd mympd[1394]: ERROR    webserver a8e20  1 mongoose.c:10974:tls_err_cb    35 548127465920:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../ssl/record/rec_layer_s3.c:1562:SSL alert number 46
May 02 18:28:39 mpd mympd[1394]: ERROR    webserver a8e20  1 mongoose.c:1363:mg_error       35 17 tls hs: rc -1, err 1
May 02 18:28:39 mpd mympd[1394]: ERROR    webserver a8ef0  1 mongoose.c:10974:tls_err_cb    36 548127465920:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../ssl/record/rec_layer_s3.c:1562:SSL alert number 46
May 02 18:28:39 mpd mympd[1394]: ERROR    webserver a8ef0  1 mongoose.c:1363:mg_error       36 17 tls hs: rc -1, err 1
May 02 18:28:39 mpd mympd[1394]: ERROR    webserver a8fba  1 mongoose.c:10974:tls_err_cb    37 548127465920:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../ssl/record/rec_layer_s3.c:1562:SSL alert number 46
May 02 18:28:39 mpd mympd[1394]: ERROR    webserver a8fba  1 mongoose.c:1363:mg_error       37 17 tls hs: rc -1, err 1
May 02 18:28:39 mpd mympd[1394]: ERROR    webserver a9093  1 mongoose.c:10974:tls_err_cb    38 548127465920:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../ssl/record/rec_layer_s3.c:1562:SSL alert number 46
May 02 18:28:39 mpd mympd[1394]: ERROR    webserver a9094  1 mongoose.c:1363:mg_error       38 17 tls hs: rc -1, err 1
May 02 18:28:40 mpd mympd[1394]: ERROR    webserver a91fd  1 mongoose.c:10974:tls_err_cb    39 548127465920:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../ssl/record/rec_layer_s3.c:1562:SSL alert number 46
May 02 18:28:40 mpd mympd[1394]: ERROR    webserver a91fd  1 mongoose.c:1363:mg_error       39 17 tls hs: rc -1, err 1
 
**Configuration (please attach if it can be useful)**

 - tarball of /var/lib/mympd/state (``tar -cf mympd_state.tar /var/lib/mympd/state``)
 - tarball of /var/lib/mympd/config (``tar -cf mympd_config.tar /var/lib/mympd/config``)
 - `mpd.conf` 

**Additional context**

**Comment by loop333** [comment] 2024-05-02 17:46
Uncaught SyntaxError: Unexpected end of input (at combined.js:14:1):
caused by
myMPD/htdocs/js/viewQueueCurrent.js:96:
if (features.featAdvqueue === false ||   **// always sorted by priority**

**Comment by GK-774** [comment] 2024-05-02 18:32
Same here on Linux (running directly on the same machine) gives just the green start screen with logo with a fresh install (/var/lib/mympd removed before starting the first time). Reverted back to 14.1.2 which works perfect on the same environment.

**Comment by GK-774** [comment] 2024-05-02 18:43
Update:  Just built 15.0.1 (devel) and this one works as expected so far, although it currently should be basically the same. Seems something is broken in the master branch.

**Comment by loop333** [comment] 2024-05-02 18:47
debug build works well on both branches because it doesn't use minify js

**Comment by GK-774** [comment] 2024-05-02 18:50
Well, "View settings" get not applied after clicking "Apply".

**Comment by loop333** [comment] 2024-05-02 18:51
> Well, "View settings" get not applied after clicking "Apply".

so I see

**Comment by GK-774** [comment] 2024-05-02 19:02
In album view and playback view the view settings are not applied and saved, the other views appear to work ok.

**Comment by jcorporation** [comment] 2024-05-02 19:38
It seems here are various bugs found.

> alert certificate unknown:../ssl/record/rec_layer_s3.c:1562:SSL alert number 46

This is a expected error message if the browser does not trust the certificate. It should not prevent myMPD to work correctly.

> Uncaught SyntaxError: Unexpected end of input (at combined.js:14:1):

This is indeed a issue with JavaScript minification that only occurs for the master branch. Fixed with ce694ea

> "View settings" get not applied after clicking "Apply".

I could reproduce it for the playback view. Fixed with b9f6e4f

**Closed** 2024-05-02 21:35 UTC
Labels: bug
