### ISSUE TITLE
Long URI out of box in Queue

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#321] opened 2020-08-29 12:26 UTC
myMPD version: 6.6.0

As attached.

![2020-08-29-210421_1600x900_scrot](https://user-images.githubusercontent.com/12131158/91636796-45508c00-ea3e-11ea-985f-00d244ced373.png)

**Comment by jcorporation** [comment] 2020-08-29 16:58
Seems to be a regression of: Change current hyphen behaviour #279

**Comment by jcorporation** [comment] 2020-08-30 09:36
`word-wrap: break-word` is not working in chrome, is now fixed in devel.

**Closed by jcorporation** 2020-08-30 09:36 UTC
Labels: bug
