### ISSUE TITLE
Missing many albums in "browse" page

### ISSUE THREAD

**Issue by DoDiesis** [jcorporation/myMPD#393] opened 2020-12-29 09:04 UTC
**Versions**
myMPD version: 6.9.1
MPD version: 0.22.3
Environment: Archlinux, fully up to date

**Description**
I have a collection of about 100 of disks, ripped and stored in their own directories, in flac format, with all the usual tags Abum, AlbumArtist, Artits, Date and so on. All the Albums have their own cover, managed by mpd, using the cover.jpg image stored in the albums directories.
 The listing by Album only shows a very few of them. I didn't find any common denominator on the shown, and not shown albums. Some album with "exotic" characters in their names are shown, other albums with only plain ASCII characters are skipped. Other clients show all of the albums. The command "mpc list" lists all of the albums.
Furthermore, if, for example, I first select "Artist", myMPD correclty show all of the artists

![image](https://user-images.githubusercontent.com/76726999/103271634-0cf49680-49bb-11eb-956d-c6522b17f8fa.png)

But, if now, I select an artist, it only shows an empty list:
![image](https://user-images.githubusercontent.com/76726999/103271700-37deea80-49bb-11eb-8975-b9eaa5a0f5e6.png)

**Expected behavior**
I should see the Albums/Tracks

**Server plattform (please complete the following information):**
 - OS: Linux
 - OS version: Linux rarch 5.9.14-arch1-1 #1 SMP PREEMPT Sat, 12 Dec 2020 14:37:12 +0000 x86_64 GNU/Linux
 - Plattform: x86_64 (AMD Ryzen 5)
 - MPD version:0.22.3

**Client plattform (please complete the following information):**
 (same as server)
 - Device: Desktop PC
 - OS: Archlinux
 - Browser: Chromium 7.0.4280.88 (Official Build) Arch Linux (64-bit) and Firefox 84.0.1 (64-bit)
 - Browser version: Chromium 7.0.4280.88 / Firefox 84.0.1

My mobile phone
 - Device: Android Mobile
 - OS: Android
 - Browser: Firefox
 - Browser version: 84.1.2

**Debug logs (please attach if it can be useful)**
When I select Artis "Baldassarre Galuppi"
Dec 29 09:52:42 rarch mympd[4160]: VERBOSE  webserver /home/roby/develop/AUR/mympd/src/myMPD-6.9.1/src/web_server.c:321: HTTP request (8): /api
Dec 29 09:52:42 rarch mympd[4160]: DEBUG    webserver /home/roby/develop/AUR/mympd/src/myMPD-6.9.1/src/web_server.c:491: API request (8): {"jsonrpc":"2.0","id":0,"method":"MPD_API_DATABASE_GET_ALBUMS","params":{"offset":"0","searchstr":"(Artist == 'Baldassarre Galuppi')","filter":"Album","sort":"AlbumArtist","sortdesc":false}}
Dec 29 09:52:42 rarch mympd[4160]: VERBOSE  webserver /home/roby/develop/AUR/mympd/src/myMPD-6.9.1/src/web_server.c:501: API request (8): MPD_API_DATABASE_GET_ALBUMS
Dec 29 09:52:42 rarch mympd[4160]: VERBOSE  webserver /home/roby/develop/AUR/mympd/src/myMPD-6.9.1/src/web_server.c:321: HTTP request (6): /assets/appicon-192.png
Dec 29 09:52:42 rarch mympd[4160]: DEBUG    mpdclient /home/roby/develop/AUR/mympd/src/myMPD-6.9.1/src/mpd_client.c:345: Leaving mpd idle mode
Dec 29 09:52:42 rarch mympd[4160]: DEBUG    mpdclient /home/roby/develop/AUR/mympd/src/myMPD-6.9.1/src/mpd_client.c:380: Handle request
Dec 29 09:52:42 rarch mympd[4160]: VERBOSE  mpdclient /home/roby/develop/AUR/mympd/src/myMPD-6.9.1/src/mpd_client/mpd_client_api.c:66: MPD CLIENT API request (8)(0) MPD_API_DATABASE_GET_ALBUMS: {"jsonrpc":"2.0","id":0,"method":"MPD_API_DATABASE_GET_ALBUMS","params":{"offset":"0","searchstr":"(Artist == 'Baldassarre Galuppi')","filter":"Album","sort":"AlbumArtist","sortdesc":false}}
Dec 29 09:52:42 rarch mympd[4160]: DEBUG    mpdclient /home/roby/develop/AUR/mympd/src/myMPD-6.9.1/src/mpd_client/mpd_client_api.c:905: Push response to web_server_queue for connection 8: {"jsonrpc":"2.0","id":0,"result":{"method":"MPD_API_DATABASE_GET_ALBUMS","data":[],"totalEntities":-1,"returnedEntities":0,"offset":0,"filter":"Album","searchstr":"(Artist == 'Baldassarre Galuppi')","sort":"AlbumArtist","sortdesc":false,"tag":"Album"}}
Dec 29 09:52:42 rarch mympd[4160]: DEBUG    mpdclient /home/roby/develop/AUR/mympd/src/myMPD-6.9.1/src/mpd_client.c:391: Entering mpd idle mode
Dec 29 09:52:42 rarch mympd[4160]: DEBUG    webserver /home/roby/develop/AUR/mympd/src/myMPD-6.9.1/src/web_server.c:248: Sending response to conn_id 8: {"jsonrpc":"2.0","id":0,"result":{"method":"MPD_API_DATABASE_GET_ALBUMS","data":[],"totalEntities":-1,"returnedEntities":0,"offset":0,"filter":"Album","searchstr":"(Artist == 'Baldassarre Galuppi')","sort":"AlbumArtist","sortdesc":false,"tag":"Album"}}

**Other Debug logs (please attach if it can be useful)**
When I select Albums and only see a few of them.

Dec 29 09:52:33 rarch mympd[4160]: VERBOSE  webserver /home/roby/develop/AUR/mympd/src/myMPD-6.9.1/src/web_server.c:501: API request (8): MPD_API_DATABASE_TAG_LIST
Dec 29 09:52:33 rarch mympd[4160]: VERBOSE  webserver /home/roby/develop/AUR/mympd/src/myMPD-6.9.1/src/web_server.c:321: HTTP request (6): /assets/appicon-192.png
Dec 29 09:52:33 rarch mympd[4160]: DEBUG    mpdclient /home/roby/develop/AUR/mympd/src/myMPD-6.9.1/src/mpd_client.c:345: Leaving mpd idle mode
Dec 29 09:52:33 rarch mympd[4160]: DEBUG    mpdclient /home/roby/develop/AUR/mympd/src/myMPD-6.9.1/src/mpd_client.c:380: Handle request
Dec 29 09:52:33 rarch mympd[4160]: VERBOSE  mpdclient /home/roby/develop/AUR/mympd/src/myMPD-6.9.1/src/mpd_client/mpd_client_api.c:66: MPD CLIENT API request (8)(0) MPD_API_DATABASE_TAG_LIST: {"jsonrpc":"2.0","id":0,"method":"MPD_API_DATABASE_TAG_LIST","params":{"offset":"0","searchstr":"","filter":"Artist","sort":"Artist","sortdesc":false,"tag":"Artist"}}
Dec 29 09:52:33 rarch mympd[4160]: DEBUG    mpdclient /home/roby/develop/AUR/mympd/src/myMPD-6.9.1/src/mpd_client/mpd_client_browse.c:500: Can not open directory "/var/lib/mympd/pics/Artist": No such file or directory
Dec 29 09:52:33 rarch mympd[4160]: DEBUG    mpdclient /home/roby/develop/AUR/mympd/src/myMPD-6.9.1/src/mpd_client/mpd_client_api.c:905: Push response to web_server_queue for connection 8: {"jsonrpc":"2.0","id":0,"result":{"method":"MPD_API_DATABASE_TAG_LIST","data":[{"value":"Alfred Cortot (anni 20) - Conversione MIDI da rullo Duo-Art"},{"value":"Anonimo Italiano (19th century)"},{"value":"Antonio Vivaldi"},{"value":"Antonín Dvořák"},{"value":"Arcangelo Corelli"},{"value":"Baldassarre Galuppi"},{"value":"Bedřich Smetana"},{"value":"Béla Bartók"},{"value":"Claude Debussy"},{"value":"Clavicembalo e Calvicembalo MIDI"},{"value":"Edvard Grieg"},{"value":"Erik Satie"},{"value":"Felix Mendelssohn"},{"value":"Ferdinando Bonazzi"},{"value":"Francesco Canneti"},{"value":"Franz Liszt"},{"value":"Franz Schubert"},{"value":"Fryderyk Chopin"},{"value":"Georg Philipp Telemann"},{"value":"George Frideric Handel"},{"value":"George Gershwin"},{"value":"Giovanni Allevi"},{"value":"Giuseppe Busi"},{"value":"Gustav Mahler"},{"value":"Il computer come sec...
Dec 29 09:52:33 rarch mympd[4160]: DEBUG    mpdclient /home/roby/develop/AUR/mympd/src/myMPD-6.9.1/src/mpd_client.c:391: Entering mpd idle mode
Dec 29 09:52:33 rarch mympd[4160]: DEBUG    webserver /home/roby/develop/AUR/mympd/src/myMPD-6.9.1/src/web_server.c:248: Sending response to conn_id 8: {"jsonrpc":"2.0","id":0,"result":{"method":"MPD_API_DATABASE_TAG_LIST","data":[{"value":"Alfred Cortot (anni 20) - Conversione MIDI da rullo Duo-Art"},{"value":"Anonimo Italiano (19th century)"},{"value":"Antonio Vivaldi"},{"value":"Antonín Dvořák"},{"value":"Arcangelo Corelli"},{"value":"Baldassarre Galuppi"},{"value":"Bedřich Smetana"},{"value":"Béla Bartók"},{"value":"Claude Debussy"},{"value":"Clavicembalo e Calvicembalo MIDI"},{"value":"Edvard Grieg"},{"value":"Erik Satie"},{"value":"Felix Mendelssohn"},{"value":"Ferdinando Bonazzi"},{"value":"Francesco Canneti"},{"value":"Franz Liszt"},{"value":"Franz Schubert"},{"value":"Fryderyk Chopin"},{"value":"Georg Philipp Telemann"},{"value":"George Frideric Handel"},{"value":"George Gershwin"},{"value":"Giovanni Allevi"},{"value":"Giuseppe Busi"},{"value":"Gustav Mahler"},{"value":"Il computer come secondo esecutore"},{"value":"Isaac Alb...
Dec 29 09:52:42 rarch mympd[4160]: VERBOSE  webserver /home/roby/develop/AUR/mympd/src/myMPD-6.9.1/src/web_server.c:321: HTTP request (8): /api

![image](https://user-images.githubusercontent.com/76726999/103271270-087bae00-49ba-11eb-842c-d6344f21de8f.png)

**Comment by jcorporation** [comment] 2020-12-29 09:10
Seems a duplicate of #379, see also: https://github.com/jcorporation/myMPD/wiki/Tags

**Comment by DoDiesis** [comment] 2020-12-29 09:27
Hello Jürgen,
it is the "disc" field.
Thank you very much for your help.
I will use myMPD in a DIgital Audio Player made by me, based on a 
stripped down version of ArchLinux and running on a small Intel Nuc 
device. The player is already made and works. Now I'm using MALP and 
MAFA on my phone for controlling it, but a built-in web server, with 
album covers support, is what I missed so far. I made some test with 
ympd, it worked, but is misses the covers, and is now abandoned-ware.

**Comment by DoDiesis** [comment] 2020-12-29 09:30
The problem is the disc field, that is mandatory with myMPD. I will update my music files.

**Closed** 2020-12-29 09:29 UTC
Labels: duplicate

**Comment by jcorporation** [comment] 2020-12-29 14:30
> The problem is the disc field, that is mandatory with myMPD. I will update my music files.

You can disable the disc tag as a workaround.
