### ISSUE TITLE
[Docker] Initial setup not working and SSL issues  

### ISSUE THREAD

**Issue by Hajuskin** [jcorporation/myMPD#675] opened 2022-02-07 17:28 UTC
myMPD version: 9.1.0

**Describe the bug**

I updated my Pi to Raspbian buster 64bit and installed a clean new image of myMPD using this docker compose:

```
services:
  mympd:
    image: ghcr.io/jcorporation/mympd/mympd
    container_name: mympd
    network_mode: "host"
    environment:
      - TZ=Europe/Berlin
      - UMASK_SET=022 #optional
      - MYMPD_SSL=false
      - MYMPD_SSL_PORT=8082
      - MYMPD_LOGLEVEL=7
    volumes:
      - /run/mpd/socket:/run/mpd/socket #optional, use if you connect to mpd using sockets
      - ./volumes/mympd:/var/lib/mympd/
      - /home/pi/Music/:/music/:ro
      - /home/pi/Music/Playlists Raspi/:/playlists/:rw
    restart: unless-stopped
```
I expected that myMPD would use these enviroment variables as initial values, but the configuration files contains the default values (eg. ssl_port = 443 and loglevel = 5)
Not sure if related and/or intended, but I noticed that the config folder in `var/lib/mympd` is owned by `root`, while all other folders are owned by `mympd`.

Beside that I can reach myMPD on port 443 and mpd is connected on `/run/mpd/socket`. My real problem starts when I change the ssl-port by editing the `ssl_port` config file. After restarting myMPD I can access the frontend on the new port, but now I get these notifications: `Websocket is disconnected` and `Websocket connection failed, trying to reconnect`
As the log shows repeated `certificate unknown` messages I downloaded the CA certificate and imported it into chrome, but it makes no difference (and I still get ssl warnings in chome).

**Server plattform (please complete the following information):**
 - myMPD running in docker
 - OS: raspberrypi os
 - OS version: 5.10.92-v8+
 - Plattform: aarch64
 - MPD version: 0.23.5

**Debug logs (please attach if it can be usefull)**
[mympd_logs.txt](https://github.com/jcorporation/myMPD/files/8017205/mympd_logs.txt)
[mpd.log](https://github.com/jcorporation/myMPD/files/8017207/mpd.log)

 
**Configuration (please attach if it can be usefull)**
[mympd_state.tar.gz](https://github.com/jcorporation/myMPD/files/8017367/mympd_state.tar.gz)
[mympd_config.tar.gz](https://github.com/jcorporation/myMPD/files/8017369/mympd_config.tar.gz)
[mpd.conf.gz](https://github.com/jcorporation/myMPD/files/8017396/mpd.conf.gz)

**Comment by jcorporation** [comment] 2022-02-07 18:43
It seems this are two different issues.

1)
Environment variables: I could reproduce it. myMPD reads the environment only if it creates the /var/lib/mympd directory. In a container deployment this directory is often mapped as a volume. I changed the behavior of myMPD to read the environment variables if it creates the /var/lib/mympd/config directory. This should fix this issue.

2)
I could not reproduce your issue. Changing the ssl_port works seamlessly in my environment. Importing the ca certificate is not necessary. Some questions:
- works ssl if you leave the port on 443?
- which browser / version?
- are any errors in the browser console?
- tried another browser or client device?

> SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:ssl/record/rec_layer_s3.c:1543:SSL alert number 46

This could be a hint that the browser does not use ssl to connect to the websocket. Please open the developer tools of your browser, open the network tab and search for a request to `/ws/`. Firefox shows this request: `wss://localhost:8443/ws/`in

**Comment by Hajuskin** [comment] 2022-02-07 20:52
I noticed that only port 8082 has problems connecting to the websocket, I tested with other random ports and they work fine. I used port 8082 with my oldinstallation of myMPD, so I guess the problem is more likely to be found in my network than in myMPD.
But for good messure, this is the console output (Chrome 98.0.4758.81 on Win 10):
Port 443:
```
An SSL certificate error occurred when fetching the script.
combined.js:8 ERROR: ServiceWorker registration failed: SecurityError: Failed to register a ServiceWorker for scope ('https://192.168.1.3/') with script ('https://192.168.1.3/sw.js'): An SSL certificate error occurred when fetching the script.
logLog @ combined.js:8
logError @ combined.js:8
(anonym) @ combined.js:8
Promise.then (async)
(anonym) @ combined.js:8
load (async)
appInitStart @ combined.js:8
(anonym) @ combined.js:8
```
Port 8082:
```
An SSL certificate error occurred when fetching the script.
combined.js:8 ERROR: ServiceWorker registration failed: SecurityError: Failed to register a ServiceWorker for scope ('https://192.168.1.3:8082/') with script ('https://192.168.1.3:8082/sw.js'): An SSL certificate error occurred when fetching the script.
logLog @ combined.js:8
logError @ combined.js:8
(anonym) @ combined.js:8
Promise.then (async)
(anonym) @ combined.js:8
load (async)
appInitStart @ combined.js:8
(anonym) @ combined.js:8
combined.js:8 WebSocket connection to 'wss://192.168.1.3:8082/ws/' failed: 
webSocketConnect @ combined.js:8
(anonym) @ combined.js:8
combined.js:8 ERROR: Websocket error occured
logLog @ combined.js:8
logError @ combined.js:8
socket.onerror @ combined.js:8
error (async)
webSocketConnect @ combined.js:8
(anonym) @ combined.js:8
setTimeout (async)
(anonym) @ combined.js:8
ajaxRequest.onreadystatechange @ combined.js:8
XMLHttpRequest.send (async)
sendAPI @ combined.js:8
appInitStart @ combined.js:8
(anonym) @ combined.js:8
combined.js:8 ERROR: Websocket connection closed: 1006
logLog @ combined.js:8
logError @ combined.js:8
socket.onclose @ combined.js:8
combined.js:8 WebSocket connection to 'wss://192.168.1.3:8082/ws/' failed: 
webSocketConnect @ combined.js:8
(anonym) @ combined.js:8
combined.js:8 ERROR: Websocket error occured
logLog @ combined.js:8
logError @ combined.js:8
socket.onerror @ combined.js:8
error (async)
webSocketConnect @ combined.js:8
(anonym) @ combined.js:8
setTimeout (async)
socket.onclose @ combined.js:8
combined.js:8 ERROR: Websocket connection closed: 1006
logLog @ combined.js:8
logError @ combined.js:8
socket.onclose @ combined.js:8
combined.js:8 WebSocket connection to 'wss://192.168.1.3:8082/ws/' failed: 
webSocketConnect @ combined.js:8
(anonym) @ combined.js:8
combined.js:8 ERROR: Websocket error occured
logLog @ combined.js:8
logError @ combined.js:8
socket.onerror @ combined.js:8
error (async)
webSocketConnect @ combined.js:8
(anonym) @ combined.js:8
setTimeout (async)
socket.onclose @ combined.js:8
combined.js:8 ERROR: Websocket connection closed: 1006
logLog @ combined.js:8
logError @ combined.js:8
socket.onclose @ combined.js:8
combined.js:8 ERROR: Illegal response for request: {"jsonrpc":"2.0","id":0,"method":"MYMPD_API_PLAYER_STATE","params":{}}
logLog @ combined.js:8
logError @ combined.js:8
ajaxRequest.onreadystatechange @ combined.js:8
XMLHttpRequest.send (async)
sendAPI @ combined.js:8
(anonym) @ combined.js:8
combined.js:8 ERROR: Response code: 0
logLog @ combined.js:8
logError @ combined.js:8
ajaxRequest.onreadystatechange @ combined.js:8
XMLHttpRequest.send (async)
sendAPI @ combined.js:8
(anonym) @ combined.js:8
combined.js:8 ERROR: Response length: 0
logLog @ combined.js:8
logError @ combined.js:8
ajaxRequest.onreadystatechange @ combined.js:8
XMLHttpRequest.send (async)
sendAPI @ combined.js:8
(anonym) @ combined.js:8
combined.js:8 POST https://192.168.1.3:8082/api/ net::ERR_CONNECTION_REFUSED
sendAPI @ combined.js:8
(anonym) @ combined.js:8
combined.js:8 WebSocket connection to 'wss://192.168.1.3:8082/ws/' failed: 
webSocketConnect @ combined.js:8
(anonym) @ combined.js:8
combined.js:8 ERROR: Websocket error occured
logLog @ combined.js:8
logError @ combined.js:8
socket.onerror @ combined.js:8
error (async)
webSocketConnect @ combined.js:8
(anonym) @ combined.js:8
setTimeout (async)
socket.onclose @ combined.js:8
combined.js:8 ERROR: Websocket connection closed: 1006
logLog @ combined.js:8
logError @ combined.js:8
socket.onclose @ combined.js:8
combined.js:8 WebSocket connection to 'wss://192.168.1.3:8082/ws/' failed: 
webSocketConnect @ combined.js:8
(anonym) @ combined.js:8
combined.js:8 ERROR: Websocket error occured
logLog @ combined.js:8
logError @ combined.js:8
socket.onerror @ combined.js:8
error (async)
webSocketConnect @ combined.js:8
(anonym) @ combined.js:8
setTimeout (async)
socket.onclose @ combined.js:8
combined.js:8 ERROR: Websocket connection closed: 1006
logLog @ combined.js:8
logError @ combined.js:8
socket.onclose @ combined.js:8
combined.js:8 WebSocket connection to 'wss://192.168.1.3:8082/ws/' failed: 
webSocketConnect @ combined.js:8
(anonym) @ combined.js:8
combined.js:8 ERROR: Websocket error occured
logLog @ combined.js:8
logError @ combined.js:8
socket.onerror @ combined.js:8
error (async)
webSocketConnect @ combined.js:8
(anonym) @ combined.js:8
setTimeout (async)
socket.onclose @ combined.js:8
combined.js:8 ERROR: Websocket connection closed: 1006
logLog @ combined.js:8
logError @ combined.js:8
socket.onclose @ combined.js:8
combined.js:8 WebSocket connection to 'wss://192.168.1.3:8082/ws/' failed: 
webSocketConnect @ combined.js:8
(anonym) @ combined.js:8
combined.js:8 ERROR: Websocket error occured
logLog @ combined.js:8
logError @ combined.js:8
socket.onerror @ combined.js:8
.
.
.
```
Both starts with `An SSL certificate error occurred when fetching the script.`, this I guess is because of the missing CA certificate?
I had no luck importing the certificate (also tried to regenerate it), I still get `NET::ERR_CERT_COMMON_NAME_INVALID` when opening the page.

**Comment by Hajuskin** [comment] 2022-02-07 21:13
So the port 8082 problem is solved, I still had the old instance of myMPD installed as an app in chrome, after removing it port 8082 works again.

Now there's just the certificate issue,  this is what I get when opening myMPD:
![2022-02-07_221111](https://user-images.githubusercontent.com/51139914/152872672-b4617f9f-48cc-4737-b59e-db150413a460.png)
![2022-02-07_221124](https://user-images.githubusercontent.com/51139914/152872685-135c1ccf-322a-4ef8-8d77-c75ce3732a1d.png)

**Comment by jcorporation** [comment] 2022-02-07 21:29
You must import the myMPD CA certificate, not the server certificate.

You connect with an ip-address to myMPD. Please check if the ip-address is in the subject alternative name of the certificate, if not: https://jcorporation.github.io/myMPD/configuration/ssl

**Comment by Hajuskin** [comment] 2022-02-07 23:06
> Looking at your docker compose file:
> 
> ```
>       - MYMPD_SSL=false
>       - MYMPD_SSL_PORT=8082
> ```
> 
> This can not work. You must set MYMPD_SSL=true if you want SSL over port 8082.

You're right, I tested a lot of settings, this one was copied from [the documentation](https://jcorporation.github.io/myMPD/installation/docker). But as the environment variables were ignored this had no effect anyway. 


Just to be sure this is what I did:

1. stoped myMPD
2. removed `/var/lib/mympd/ssl/server.pem` and `/var/lib/mympd/ssl/server.key`
3. wrote `IP:192.168.1.3` to `/var/lib/mympd/config/ssl_san` (ip of my Raspberry)
4. restart myMPD and downloaded `ca.crt`
5. import `ca.crt` into chrome
6. restart myMPD

This is the result:
![2022-02-07_235613](https://user-images.githubusercontent.com/51139914/152886330-faeed035-c991-4bc5-adc8-ffb09f248df6.png)
![2022-02-07_235645](https://user-images.githubusercontent.com/51139914/152886342-1ef7e23a-1b05-4edd-ae0a-51bffe61a733.png)
![2022-02-07_235659](https://user-images.githubusercontent.com/51139914/152886354-02c1c094-87ce-4d7f-bd01-da8fdb772dea.png)
![2022-02-07_235713](https://user-images.githubusercontent.com/51139914/152886367-285d6dc0-0b9a-44b4-8eb5-23088093d646.png)

**Comment by Hajuskin** [comment] 2022-02-08 18:04
Certificate with empty `ssl_san`:
[san_empty.txt](https://github.com/jcorporation/myMPD/files/8026318/san_empty.txt)

`ssl_san` populated:
[san_populated.txt](https://github.com/jcorporation/myMPD/files/8026320/san_populated.txt)

Log seems fine:
```
empty ssl_san
2022-02-08T17:59:18.880157769Z INFO     mympd     OpenSSL 1.1.1l  24 Aug 2021
2022-02-08T17:59:18.880358876Z DEBUG    mympd     Setting dns server to udp://192.168.1.3:53
2022-02-08T17:59:18.880808327Z NOTICE   mympd     Listening on http://0.0.0.0:80
2022-02-08T17:59:18.881131449Z NOTICE   mympd     Listening on https://0.0.0.0:8082
2022-02-08T17:59:18.881160929Z NOTICE   mympd     Serving files from "/var/lib/mympd/empty"
2022-02-08T17:59:18.881177429Z NOTICE   mympd     Droping privileges to user "mympd"
2022-02-08T17:59:18.881886967Z NOTICE   mympd     SSL cert dir: "/var/lib/mympd/ssl"
2022-02-08T17:59:18.885185458Z NOTICE   mympd     CA certificate and private key found
2022-02-08T17:59:18.885250012Z DEBUG    mympd     Certificate /var/lib/mympd/ssl/ca.pem expires in 3648 days
2022-02-08T17:59:18.885418804Z NOTICE   mympd     Creating server certificate
2022-02-08T17:59:19.268591634Z NOTICE   mympd     Set server certificate san to: DNS:localhost,DNS:raspberrypi,IP:127.0.0.1,IP:192.168.1.3,IP:172.17.0.1,IP:172.18.0.1,IP:169.254.12.25,IP:169.254.49.95,IP:169.254.136.105,IP:169.254.215.64,IP:169.254.33.208,IP:::1,IP:fe80::4aca:9fee:26c9:eb46%eth0,IP:fe80::42:e0ff:fee8:ccce%br-47f6840a8ebf,IP:fe80::7000:a7ff:fe17:58fb%veth59971b4,IP:fe80::890c:cfaf:ad73:3e60%vethb159dfd,IP:fe80::9403:8bff:feb6:f182%veth4b32d21,IP:fe80::852:69ff:fe40:8ddd%veth519745f, IP:192.168.1.3

ssl_san with IP:192.168.1.3
2022-02-08T17:52:06.463689173Z INFO     mympd     OpenSSL 1.1.1l  24 Aug 2021
2022-02-08T17:52:06.463933950Z DEBUG    mympd     Setting dns server to udp://192.168.1.3:53
2022-02-08T17:52:06.464095765Z NOTICE   mympd     Listening on http://0.0.0.0:80
2022-02-08T17:52:06.464220265Z NOTICE   mympd     Listening on https://0.0.0.0:8082
2022-02-08T17:52:06.464275302Z NOTICE   mympd     Serving files from "/var/lib/mympd/empty"
2022-02-08T17:52:06.464333450Z NOTICE   mympd     Droping privileges to user "mympd"
2022-02-08T17:52:06.465580209Z NOTICE   mympd     SSL cert dir: "/var/lib/mympd/ssl"
2022-02-08T17:52:06.469450245Z NOTICE   mympd     CA certificate and private key found
2022-02-08T17:52:06.469546134Z DEBUG    mympd     Certificate /var/lib/mympd/ssl/ca.pem expires in 3648 days
2022-02-08T17:52:06.469563837Z NOTICE   mympd     Creating server certificate
2022-02-08T17:52:06.668468767Z NOTICE   mympd     Set server certificate san to: DNS:localhost,DNS:raspberrypi,IP:127.0.0.1,IP:192.168.1.3,IP:172.17.0.1,IP:172.18.0.1,IP:169.254.12.25,IP:169.254.49.95,IP:169.254.136.105,IP:169.254.215.64,IP:169.254.33.208,IP:::1,IP:fe80::4aca:9fee:26c9:eb46%eth0,IP:fe80::42:e0ff:fee8:ccce%br-47f6840a8ebf,IP:fe80::7000:a7ff:fe17:58fb%veth59971b4,IP:fe80::890c:cfaf:ad73:3e60%vethb159dfd,IP:fe80::9403:8bff:feb6:f182%veth4b32d21,IP:fe80::852:69ff:fe40:8ddd%veth519745f

```

**Comment by jcorporation** [comment] 2022-02-08 18:21
Strange, there is no X509v3 Subject Alternative Name field in the certificates.

**Comment by Hajuskin** [comment] 2022-02-08 18:23
Yes, and log didn't state `Adding IP:192.168.1.3 to SAN`, but it is listed in `Set server certificate san to...`

**Comment by jcorporation** [comment] 2022-02-08 18:47
I think I found the error. The zone identifiers of the ipv6 addresses are invalid for SAN and must be removed. This is fixed in devel already. Can you test the devel branch?

**Comment by Hajuskin** [comment] 2022-02-08 19:01
Log:
```
2022-02-08T18:52:55.706024296Z NOTICE   mympd     SSL cert dir: "/var/lib/mympd/ssl"
2022-02-08T18:52:55.708754213Z NOTICE   mympd     CA certificate and private key found
2022-02-08T18:52:55.708818119Z DEBUG    mympd     Certificate /var/lib/mympd/ssl/ca.pem expires in 3648 days
2022-02-08T18:52:55.708834433Z NOTICE   mympd     Creating server certificate
2022-02-08T18:52:56.323109867Z DEBUG    mympd     Adding DNS:localhost to SAN
2022-02-08T18:52:56.323300955Z DEBUG    mympd     Adding DNS:raspberrypi to SAN
2022-02-08T18:52:56.324039326Z DEBUG    mympd     Adding IP:127.0.0.1 to SAN
2022-02-08T18:52:56.324115454Z DEBUG    mympd     Adding IP:192.168.1.3 to SAN
2022-02-08T18:52:56.324133861Z DEBUG    mympd     Adding IP:172.17.0.1 to SAN
2022-02-08T18:52:56.324215211Z DEBUG    mympd     Adding IP:172.18.0.1 to SAN
2022-02-08T18:52:56.324250432Z DEBUG    mympd     Adding IP:169.254.12.25 to SAN
2022-02-08T18:52:56.324284339Z DEBUG    mympd     Adding IP:169.254.49.95 to SAN
2022-02-08T18:52:56.324395855Z DEBUG    mympd     Adding IP:169.254.136.105 to SAN
2022-02-08T18:52:56.324475798Z DEBUG    mympd     Adding IP:169.254.215.64 to SAN
2022-02-08T18:52:56.324541518Z DEBUG    mympd     Adding IP:169.254.33.208 to SAN
2022-02-08T18:52:56.324580943Z DEBUG    mympd     Adding IP:::1 to SAN
2022-02-08T18:52:56.324744736Z DEBUG    mympd     Adding IP:fe80::4aca:9fee:26c9:eb46 to SAN
2022-02-08T18:52:56.324894121Z DEBUG    mympd     Adding IP:fe80::42:e0ff:fee8:ccce to SAN
2022-02-08T18:52:56.325051691Z DEBUG    mympd     Adding IP:fe80::7000:a7ff:fe17:58fb to SAN
2022-02-08T18:52:56.325187873Z DEBUG    mympd     Adding IP:fe80::890c:cfaf:ad73:3e60 to SAN
2022-02-08T18:52:56.325340777Z DEBUG    mympd     Adding IP:fe80::9403:8bff:feb6:f182 to SAN
2022-02-08T18:52:56.325478403Z DEBUG    mympd     Adding IP:fe80::852:69ff:fe40:8ddd to SAN
2022-02-08T18:52:56.325630048Z DEBUG    mympd     Adding IP:fe80::d053:30ff:fe1c:3468 to SAN
2022-02-08T18:52:56.325787674Z DEBUG    mympd     Adding custom san: IP:192.168.1.3
2022-02-08T18:52:56.325901708Z NOTICE   mympd     Set server certificate san to: DNS:localhost,DNS:raspberrypi,IP:127.0.0.1,IP:192.168.1.3,IP:172.17.0.1,IP:172.18.0.1,IP:169.254.12.25,IP:169.254.49.95,IP:169.254.136.105,IP:169.254.215.64,IP:169.254.33.208,IP:::1,IP:fe80::4aca:9fee:26c9:eb46,IP:fe80::42:e0ff:fee8:ccce,IP:fe80::7000:a7ff:fe17:58fb,IP:fe80::890c:cfaf:ad73:3e60,IP:fe80::9403:8bff:feb6:f182,IP:fe80::852:69ff:fe40:8ddd,IP:fe80::d053:30ff:fe1c:3468,IP:192.168.1.3

```
and openssl output:
```
            X509v3 Subject Alternative Name: 
                DNS:localhost, DNS:raspberrypi, IP Address:127.0.0.1, IP Address:192.168.1.3, IP Address:172.17.0.1, IP Address:172.18.0.1, IP Address:169.254.12.25, IP Address:169.254.49.95, IP Address:169.254.136.105, IP Address:169.254.215.64, IP Address:169.254.33.208, IP Address:0:0:0:0:0:0:0:1, IP Address:FE80:0:0:0:4ACA:9FEE:26C9:EB46, IP Address:FE80:0:0:0:42:E0FF:FEE8:CCCE, IP Address:FE80:0:0:0:7000:A7FF:FE17:58FB, IP Address:FE80:0:0:0:890C:CFAF:AD73:3E60, IP Address:FE80:0:0:0:9403:8BFF:FEB6:F182, IP Address:FE80:0:0:0:852:69FF:FE40:8DDD, IP Address:FE80:0:0:0:D053:30FF:FE1C:3468, IP Address:192.168.1.3
```
And as a result the ssl warning has gone ✓
Thank you very much!

**Comment by jcorporation** [comment] 2022-02-08 19:04
Great, I close the issue.

**Closed by jcorporation** 2022-02-08 19:04 UTC
Labels: bug
