### ISSUE TITLE
Can not remove homeicons

### ISSUE THREAD

**Issue by avalx** [jcorporation/myMPD#918] opened 2022-12-05 12:24 UTC
myMPD version: 10.2.0
**Describe the bug**

 Deleting homeicons seem to not be persistent. I tried to remove one of the icons from the Home page and this seems to work - the icon is gone.  But after mympd restart the same icon is still there. I've checked the home_list file and the entry for this icon is not removed.

**To Reproduce**

1. Go to 'Home!
2. Click on Right click on one of the icons -> Homeicon -> Delete Homeicon (the icon is not there anymore)
3. Restart mympd
4. Go to 'Home' and the deleted icon is still there

**Expected behavior**

Delete homeicon should be persistent across restarts of mympd.

**Screenshots**

**Server plattform (please complete the following information):**
 - OS: [e.g. DietPI] Fedora
 - OS version [e.g. 6.26] 37
 - Plattform: [e.g. x86_64]
 - MPD version: [e.g. 0.21.16] 	0.23.5

**Client plattform (please complete the following information):**
 - Device: [e.g. iPhone6, Laptop] PC
 - OS: [e.g. iOS, Windows 10, Ubuntu Linux 19.10] Windows 10
 - Browser [e.g. chrome, safari] Firefox
 - Browser version [e.g. 22] latest

**Debug logs (please attach if it can be useful)**

Look at https://jcorporation.github.io/myMPD/debug

 - myMPD debug log
 - MPD verbose log
 - Browser error console
 - Browser network console
 
**Configuration (please attach if it can be useful)**

 - tarball of /var/lib/mympd/state (``tar -cf mympd_state.tar /var/lib/mympd/state``)
 - tarball of /var/lib/mympd/config (``tar -cf mympd_config.tar /var/lib/mympd/config``)
 - `mpd.conf` 
[Download.zip](https://github.com/jcorporation/myMPD/files/10154040/Download.zip)

**Additional context**

**Comment by jcorporation** [comment] 2022-12-05 16:35
I quickly checked this and I can not reproduce it. Please provide myMPD debug logs.

myMPD writes the home_list file only on exit, not when you modify the home icons.

**Comment by avalx** [comment] 2022-12-05 17:35
> I quickly checked this and I can not reproduce it. Please provide myMPD debug logs.
> 
I'm not sure how to do this? I tried running mympd from the console (after setting log level to 7) but all I get is en error:

18:21:47 ERROR    mympd     User "mympd" does not exist
18:21:47 ERROR    mympd     Success


> myMPD writes the home_list file only on exit, not when you modify the home icons.
I did some additional testing - I removed the home_list file (from /var/lib/private/mympd/state/) and configured homeicons again. Then I did stop/start the mympd daemon but the file home_list was not created at all.

**Comment by jcorporation** [comment] 2022-12-05 18:25
Strange issue. I checked the issue on an other instance running myMPD with the new systemd service unit and can also not replicate your issue.

Can you check that `/var/lib/mympd/` is a link to `/var/lib/private/mympd/`?

You can not start mympd from the console because there is no explicit mympd user anymore. It is a systemd dynamic user.

Enable the debug log for the service:

```
#enable debug
echo 7 > /var/lib/mympd/config/loglevel`
systemctl restart mympd

#replay your problem and get logs
journalctl -u mympd

#reset loglevel
echo 5 > /var/lib/mympd/config/loglevel
systemctl restart mympd
```

**Comment by avalx** [comment] 2022-12-05 18:53
> 
> Can you check that `/var/lib/mympd/` is a link to `/var/lib/private/mympd/`?
>

Yes, that is so

> Enable the debug log for the service:
> 

This is strange indeed. I tried with the debug enabled and this is what I get in the journactl output after I stopped the mympd daemon:

Dec 05 19:40:49 sever.lan mympd[22439]: DEBUG    webserver "default": Websocket message (2): ping
Dec 05 19:40:56 sever.lan mympd[22439]: INFO     webserver HTTP connection 8 closed
Dec 05 19:41:06 sever.lan mympd[22439]: NOTICE   mympd     Signal "SIGTERM" received, exiting
Dec 05 19:41:06 sever.lan systemd[1]: Stopping mympd.service - myMPD server daemon...
Dec 05 19:41:06 sever.lan mympd[22439]: DEBUG    mympdapi  "!all!": Trigger event: mympd_stop (-3)
Dec 05 19:41:06 sever.lan mympd[22439]: INFO     mympdapi  "default": Disconnecting from mpd
Dec 05 19:41:06 sever.lan mympd[22439]: DEBUG    mympdapi  Push websocket notify to queue: "{"jsonrpc":"2.0","m>
Dec 05 19:41:06 sever.lan mympd[22439]: DEBUG    mympdapi  "default": Trigger event: mympd_disconnected (-5)
Dec 05 19:41:06 sever.lan mympd[22439]: INFO     mympdapi  Saving home icons to disc
Dec 05 19:41:06 sever.lan mympd[22439]: INFO     mympdapi  Saving timers to disc
Dec 05 19:41:06 sever.lan mympd[22439]: INFO     mympdapi  Saving triggers to disc
Dec 05 19:41:06 sever.lan mympd[22439]: INFO     mympdapi  "default": Saving last_played list to disc
Dec 05 19:41:06 sever.lan mympd[22439]: DEBUG    mympdapi  Removing timer with id 2
Dec 05 19:41:06 sever.lan mympd[22439]: DEBUG    mympdapi  Removing timer with id 1
Dec 05 19:41:06 sever.lan mympd[22439]: DEBUG    mympdapi  Freeing sticker cache
Dec 05 19:41:06 sever.lan mympd[22439]: NOTICE   mympd     Finished web server thread
Dec 05 19:41:06 sever.lan systemd[1]: mympd.service: Main process exited, code=dumped, status=11/SEGV
Dec 05 19:41:06 sever.lan systemd[1]: mympd.service: Failed with result 'core-dump'
Dec 05 19:41:06 sever.lan systemd[1]: Stopped mympd.service - myMPD server daemon.

Any idea why it might do the core-dump? Could be something with my F37 installation?

P.S. Tomorrow I wil try this on my virtual machin (F37 as well).

**Comment by avalx** [comment] 2022-12-05 19:03
Well, .... now suddenly the home_list file appeared??!! But still can not remove (or add) homeicons.

I'll try again tomorrow with a clean installation maybe.

**Comment by jcorporation** [comment] 2022-12-05 19:16
Strange, a cordeump is always bad. Too find the cause, we need a myMPD debug build and a manual start from the console.

**Comment by jcorporation** [comment] 2022-12-06 20:07
I can reproduce the segfault. It results from a compile flag from rpmbuild: `-flto=auto`.

**Comment by jcorporation** [comment] 2022-12-06 22:29
Segfault should be fixed in the devel branch.

**Comment by avalx** [comment] 2022-12-07 08:44
Great, thank you!

**Closed** 2022-12-07 08:45 UTC
Labels: bug, investigate
