### ISSUE TITLE
Newly added music not visible in Browse mode

### ISSUE THREAD

**Issue by avalx** [jcorporation/myMPD#791] opened 2022-07-05 07:27 UTC
myMPD version: 9.4.0 - devel branch

After adding some new music to my collection I don't see it in the browse mode - neither albums nor artists. Also if I try to find this particular artist/album the response is Empy List. 

On the other hand if I try the Search button on the left toolbar new music is found and I can also add it to the queue and play it. The same is true if I go to Filesystem mode and search.

**To Reproduce**

1. Add music to collection
2. Update database
3. Click on Browse
4. Sort by Last modified - Descending
5. New albums are not shown/found

**Expected behavior**

All new music shoud be visible in the browse mode

** Screenshots **

![Clipboard01](https://user-images.githubusercontent.com/22810741/177272517-8f2a1e5b-e040-403b-a571-2d9a8798d276.jpg)

![Clipboard02](https://user-images.githubusercontent.com/22810741/177272540-d9e52a68-a2e3-49b6-a799-961c3ae632e8.jpg)

![Clipboard03](https://user-images.githubusercontent.com/22810741/177272566-a4cadc5c-f510-4056-9bc0-2b93ab066dbd.jpg)

**Server plattform (please complete the following information):**
 - OS: [e.g. DietPI] Fedora
 - OS version [e.g. 6.26] 36
 - Plattform: [e.g. x86_64]
 - MPD version: [e.g. 0.21.16] 	0.23.5

**Client plattform (please complete the following information):**
 - Device: [e.g. iPhone6, Laptop] Desktop
 - OS: [e.g. iOS, Windows 10, Ubuntu Linux 19.10] Windows
 - Browser [e.g. chrome, safari] any
 - Browser version [e.g. 22]

**Debug logs (please attach if it can be usefull)**

Look at https://jcorporation.github.io/myMPD/debug

 - myMPD debug log
 - MPD verbose log
 - Browser error console
 - Browser network console
 
**Configuration (please attach if it can be usefull)**

[Download.zip](https://github.com/jcorporation/myMPD/files/9044167/Download.zip)

 - tarball of /var/lib/mympd/state (``tar -cf mympd_state.tar /var/lib/mympd/state``)
 - tarball of /var/lib/mympd/config (``tar -cf mympd_config.tar /var/lib/mympd/config``)
 - `mpd.conf` 

**Additional context**

**Comment by Emilot** [comment] 2022-07-05 09:58
Maybe because you search for "makaya" in "Album" tag and the album is called "Deciphering the message"?

**Comment by avalx** [comment] 2022-07-05 10:04
Ups, I add the wrong screenshot, sorry. 
Actually I searched in AnyTag and it's the same problem

![Clipboard01](https://user-images.githubusercontent.com/22810741/177303792-76b386dd-992b-4fb2-b0a5-e4306b0e61cc.jpg)

**Comment by Emilot** [comment] 2022-07-05 10:07
Can you see the "AlbumArtist" tag? It says also Makaya?

**Comment by jcorporation** [comment] 2022-07-05 10:08
Please add debug logs.

**Comment by avalx** [comment] 2022-07-05 10:20
> Can you see the "AlbumArtist" tag? It says also Makaya?

OK this solved the issue - AlbumArtist tag was not present. I added it and did the Rescan Database and now I see the new music in Browse view as expected.

I didn't know that this tag is mandatory for the Browse function to work properly - IMHO it shoud work also with only the Artist tag defined.

Thanks for the hint.

**Comment by jcorporation** [comment] 2022-07-05 12:59
There are pros and cons for the fallback from AlbumArtist to Artist. This implicit fallback was initially removed in v9.4.0 (devel). In the past there are some issues because of this fallback ...

myMPD defines Albums by distinct AlbumArtist+Album values. It only falls back to Artist+Album if AlbumArtist tag is generally disabled.

Documentation: https://github.com/jcorporation/myMPD/blob/devel/docs/references/tags.md

**Comment by edhelas** [comment] 2022-08-04 10:07
Answering here from #804 as it is the same issue.

I have 2500 albums in my database. Most of them are directly tagged using MusicBrainz. The tools that I'm using to tag them doesn't set albumartist if the artist is the same for the whole album.

I understand the need of albumartist when there is several artists per album but I don't have the resources to retag most of my database by forcing albumartist = artist if albumartist not available. 

Is there some performances issues related to that ?

**Comment by GK-774** [comment] 2022-08-04 12:24
I second that. I have 8388 albums (156734 songs) and I´m certainly not retagging them as a work around.
Just tried it for a band I have 12 albums from and in the search shows only the three that have AlbumArtist set, the others are silently ignored. 
Where would I need to disable AlbumArtist, in "Tags to use", "Tags to search" or "Tags to browse" or all of them?
In my view "AlbumArtist" is just an additional tag (nice for compilations) but not a replacement of "Artist".
Expected behaviour, in my view, would be, if I search "any tag" then _any_ tag shall be actually searched.

**Comment by jcorporation** [comment] 2022-08-04 16:28
If there is no Albumartist tag the album is not included in the myMPD album cache and that’s why the search can not find them.

If we include albums without albumartist tag, myMPD must map the artist tag to the albumartist tag for the albumcache. This should technically work. I test it in the v9.5.0 branch.

**Comment by jcorporation** [comment] 2022-08-04 19:46
This enhancement is now implemented in devel and quick test works for me. Can anyone test also?

**Comment by edhelas** [comment] 2022-08-04 20:18
I'd be ok to test but I'm only installing from the deb package so far. I have to check how to build it for my RPi.

**Comment by jcorporation** [comment] 2022-08-04 20:27
Build on rpi should be straight forward:
```
git clone https://github.com/jcorporation/myMPD.git
cd myMPD
git checkout v9.5.0
sudo ./build.sh installdeps
./build.sh release
release/myMPD
```

**Comment by edhelas** [comment] 2022-08-04 21:20
Yup, looks good to me :) ! I see all the albums that I was missing before. The UI looks buggy but it seems that its because its still a development version.

**Comment by jcorporation** [comment] 2022-08-04 21:37
> Yup, looks good to me :) 

Great!

> The UI looks buggy

Please report what looks bugy in another issue. In my development environment all seems fine.

Closing this issue one more time...

**Closed by jcorporation** 2022-08-04 21:37 UTC
Labels: enhancement
