### ISSUE TITLE
Version 6.8.1: Incorrect arguments when clicking on CD title

### ISSUE THREAD

**Issue by ustraub** [jcorporation/myMPD#373] opened 2020-11-25 21:06 UTC
Clicking on the CD title (see screenshot) produces the error message "Incorrect arguments"
![grafik](https://user-images.githubusercontent.com/46170211/100281443-33fa1b80-2f6a-11eb-959e-26113682e581.png)

**Comment by jcorporation** [comment] 2020-11-26 18:18
This is a duplicate of #364.

**Closed by jcorporation** 2020-11-26 18:18 UTC
Labels: duplicate
