### ISSUE TITLE
myMPD disconnects when I replace queue and play an album

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#1151] opened 2023-11-02 14:53 UTC
myMPD version: 13.0.1

**Describe the bug**

myMPD disconnects when I replace queue and play an album

**To Reproduce**

1. Go to 'Browse > Album'
2. Click on 'Replace queue and play'
3. myMPD disconnects

**Expected behavior**

Play an album

**Screenshots**

![2023-11-02-233654_1600x900_scrot](https://github.com/jcorporation/myMPD/assets/12131158/37e37573-5692-4be1-8516-92f9e3482e5b)

**Server platform (please complete the following information):**
 - OS: Ubuntu
 - OS version 22.04.3
 - Platform: x86_64
 - MPD version: 0.23.12

**Client platform (please complete the following information):**
 - Device: Laptop (same as server)
 - OS: Ubuntu Linux 22.04.3
 - Browser Firefox
 - Browser version 119

**Debug logs (please attach if it can be useful)**

[mympd.log](https://github.com/jcorporation/myMPD/files/13241045/mympd.log)
 
**Configuration (please attach if it can be useful)**

**Additional context**

Issue since version 13.0.0.
filesystem has no issue.
No problem with version 12.1.1

**Comment by jcorporation** [comment] 2023-11-02 15:02
`11월 02 23:24:35 ubuntu systemd[1]: mympd.service: Main process exited, code=killed, status=11/SEGV`

Very bad, a segfault. Please install debug symbols and provide a stack trace.

**Comment by parkmino** [comment] 2023-11-02 16:03
[mympd1.log](https://github.com/jcorporation/myMPD/files/13242008/mympd1.log)

**Comment by jcorporation** [comment] 2023-11-02 19:08
Sure that this is a debug build or the debug symbols are installed?

Try running a debug build it with valgrind:

```
./build.sh debug
valgrind --leak-check=full --exit-on-first-error=yes debug/bin/mympd
```

**Comment by parkmino** [comment] 2023-11-02 22:16
[mympd2.log](https://github.com/jcorporation/myMPD/files/13245081/mympd2.log)

**Comment by jcorporation** [comment] 2023-11-02 22:55
This was very helpful.  Fix is in devel, could you test?

**Comment by Locke** [comment] 2023-11-03 08:16
I'm affected by the same issue since the upgrade from 12.1.1-1 to 13.0.0-1, unfortunately I didn't have a chance to report this earlier.

Just for reference my stack trace:

```
                Stack trace of thread 1084:
                #0  0x00000000f76c8150 strlen (libc.so.6 + 0x7a150)
                #1  0x0000000000886624 escape_mpd_search_expression.constprop.0 (mympd + 0x76624)
                #2  0x000000000085a694 mympd_api_queue_insert_albums (mympd + 0x4a694)
                #3  0x00000000008525ac mympd_api_handler (mympd + 0x425ac)
                #4  0x0000000000829af0 mpd_client_idle_partition (mympd + 0x19af0)
                #5  0x0000000000837634 mympd_api_loop (mympd + 0x27634)
                #6  0x00000000f7b49310 start_thread (libpthread.so.0 + 0x6310)
                #7  0x00000000f7729598 n/a (libc.so.6 + 0xdb598)
```

I just tested the devel branch at 178d2a9ad861 and the issue is resolved.

The issue does not

**Comment by jcorporation** [comment] 2023-11-03 08:39
The fixed version will be released the weekend.

**Closed** 2023-11-03 08:41 UTC
Labels: bug
