### ISSUE TITLE
error "Response error: undefined" when mympd is accessed behind reverse proxy

### ISSUE THREAD

**Issue by tsunulukai** [jcorporation/myMPD#1358] opened 2024-10-09 18:45 UTC
myMPD version: 18.1.0

**Describe the bug**

Since the latest update, with myMPD running behind an nginx proxy under "https://host/myMPD/", the interface returns an error "Response error: undefined"

Using the browser inspector, the issue seems to be linked to a POST request made to https://nas/myMPD/api/Test, which gets a 502 error being sent back by nginx.

When accessing mympd without reverse proxy under "http://host:<mympdport>/", the problem does not occurs.

Error wasn't occuring with the same nginx configuration using mympd v18.0.0.
Reverting to mympd v18.0.0 fixes the issue

**Expected behavior**

myMPD should run fine behind a reverse proxy with a different root directory as "/"

**Screenshots**

![image](https://github.com/user-attachments/assets/4647b47f-2a43-4c55-8e60-c3685c659bc1)

**Server platform (please complete the following information):**
 - OS: debian
 - OS version 12.7
 - Platform: x86_64
 - MPD version: MPD v0.24 dev 124c0e66ee7b979e541828b8f809d5eebe631ab6

**Client platform (please complete the following information):**
Happens both from a Firefox browser under Windows as from Brave on Android 14.g. 22]

**Debug logs**

```
Oct 09 18:33:04 nas mympd[1637723]: ERROR    mympdapi        Unable to find partition for queue fd: 3
Oct 09 18:33:04 nas mympd[1637723]: WARN     mympdapi        Discarding request for unknown partition "Test"
```

NB: I have no partition setup named "Test", nor was my browser previously set-up to access a partition named "Test"

Look at https://jcorporation.github.io/myMPD/debug

 - myMPD debug log
 - MPD verbose log
 - Browser error console
 - Browser network console
 
**Configuration (please attach if it can be useful)**

Not sure mympd config is relevant as it was working fine with previous releases.

nginx config:
```

server {
    listen 80;
    listen 0.0.0.0:443 ssl http2;
    listen [::]:443 ssl http2;
    # myMPD
    location /myMPD/ {
      proxy_pass http://127.0.0.1:880/;
      include conf.d/params/proxy.conf;
    }
}

# cat conf.d/params/proxy.conf
proxy_redirect          off;
proxy_set_header        Host                    $http_host;
proxy_set_header        X-Real-IP               $remote_addr;
proxy_set_header        X-Forwarded-For         $proxy_add_x_forwarded_for;
proxy_set_header        X-Forwarded-Host        $http_host;
proxy_set_header        X-Forwarded-Proto       $scheme;
```

**Comment by jcorporation** [comment] 2024-10-09 19:14
That is strange, `https://nas/myMPD/api/Test` refers to a test partition. The current partition of your browser session is stored in the local storage.

Try to revert commit `80dcd0a4617621e8a44001fd2138490de84be7af` that was an update of mongoose.

**Comment by tsunulukai** [comment] 2024-10-09 19:35
reverting commit 80dcd0a4617621e8a44001fd2138490de84be7af and rebuilding fixes the issue !

**Comment by MickMorley** [comment] 2024-10-09 19:43
I use NGINX as well (SWAG) and I am getting the same error on 18.1.0, could you explain the steps I need to take in order to 

- revert commit `80dcd0a4617621e8a44001fd2138490de84be7af` and rebuild

**Comment by tsunulukai** [comment] 2024-10-09 19:52
If you're already familiar with building mympd from the source, all you need to do is:

- git clone https://github.com/jcorporation/myMPD/
- cd myMPD
- git revert 80dcd0a4617621e8a44001fd2138490de84be7af
- you'll have  an unresolved conflict with CHANGELOG.md, edit the file, resolve the conflict
- git revert --continue

From then on, you have a up to date master source tree with the problematic commit reverted. You can rebuild mympd from there and have it work as expected pending the next release.

If you need help with the build process, I would first advise you to have a look here:
https://jcorporation.github.io/myMPD/010-installation/compiling/build-sh/

**Comment by jcorporation** [comment] 2024-10-09 19:54
I just release a fixed 18.1.1 version.

**Comment by MickMorley** [comment] 2024-10-09 19:55
Ah, thank you very much for the details.  My deployment is via Github package (ghcr.io/jcorporation/mympd/mympd:latest) using Docker.  I'm guessing I have to wait until the issue is fixed in the container for testing.

**Comment by jcorporation** [comment] 2024-10-09 19:57
The images and packages are in the build state. Should be published in a few minutes.

**Comment by tsunulukai** [comment] 2024-10-09 19:58
That was wicked fast, thanks ! 👍

**Comment by jcorporation** [comment] 2024-10-09 20:05
Thas was a really ugly bug. The regressions in mongoose in this year are annoying me.

**Comment by MickMorley** [comment] 2024-10-09 20:17
I know this is closed and I appreciate the very quick fix.  Just wanted to let you know, the package is built and I've sucessfully tested it.  All is working with a NGINX reverse proxy!  

Just an FYI, after a successful page load, the message `Connected to myMPD: Partition default` appears at the bottom right, I'm guessing it has to do with the `api/default` endpoint that it couldn't hit previously.

![image](https://github.com/user-attachments/assets/76969c0a-a4e6-4963-8e1c-02a8cc3b7969)

**Comment by jcorporation** [comment] 2024-10-10 20:32
I had now a chance to debug this issue in more detail. It is indeed a behavior change of mongoose introduced by commit https://github.com/cesanta/mongoose/commit/9974be3fdc149e0477dc61b95dc2ba556fe43054. Mongoose closes the connection before the mympd_api thread has a chance to generate the response. I think this is a bug in mongoose and I opened an issue: https://github.com/cesanta/mongoose/issues/2937.

I reopened this issue to track this bug.

**Comment by jcorporation** [comment] 2024-10-11 17:37
Mongoose fixed the bug and I integrated the current master branch of mongoose. It works in my tests behind nginx. 

Can you test the devel branch?

**Comment by tsunulukai** [comment] 2024-10-11 19:04
Built & tested from devel ceb726366b744984008d99b43ceff9243459bff5
Works as expected 👍

**Comment by MickMorley** [comment] 2024-10-11 19:19
Same result, reverse proxy is working using the `devel` github container.

![image](https://github.com/user-attachments/assets/a9b343af-ac7a-4acf-b81a-fa898cae71de)

**Closed** 2024-10-11 19:27 UTC
Labels: bug, dependencies
