### ISSUE TITLE
liblua Dependancy issue on Debian package

### ISSUE THREAD

**Issue by tsunulukai** [jcorporation/myMPD#301] opened 2020-07-16 17:44 UTC
myMPD version: 6.5.1-1_amd64.deb

**Describe the bug**

When trying to install the debian package, the installation fails because it cannot resolve the dependancy "liblua5.3"
Under Debian Buster, the correct dependancy should be "liblua5.3-0"

**Server plattform (please complete the following information):**
 - OS: Debian Linux Buster (10) amd64
 - MPD version: 6.5.1-1

**Debug logs (please attach if it can be usefull)**
```
# dpkg -i mympd_6.5.1-1_amd64.deb
(Reading database ... 166666 files and directories currently installed.)
Preparing to unpack mympd_6.5.1-1_amd64.deb ...
Unpacking mympd (6.5.1-1) over (6.5.1-1) ...
dpkg: dependency problems prevent configuration of mympd:
 mympd depends on liblua5.3; however:
  Package liblua5.3 is not installed.

dpkg: error processing package mympd (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 mympd

# apt-get install liblua5.3
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package liblua5.3 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'liblua5.3' has no installation candidate

# apt show liblua5.3
Package: liblua5.3
State: not a real package (virtual)
N: Can't select candidate version from package liblua5.3 as it has no candidate
N: Can't select versions from package 'liblua5.3' as it is purely virtual
N: No packages found

# apt show liblua5.3-0
Package: liblua5.3-0
Version: 5.3.3-1.1
Priority: optional
Section: libs
Source: lua5.3
Maintainer: Enrico Tassi <gareuselesinge@debian.org>
Installed-Size: 486 kB
Depends: libc6 (>= 2.14), libgcc1 (>= 1:3.0), libstdc++6 (>= 4.1.1)
Homepage: http://www.lua.org
Tag: role::shared-lib
Download-Size: 120 kB
APT-Manual-Installed: yes
APT-Sources: http://ftp.be.debian.org/debian buster/main amd64 Packages
Description: Shared library for the Lua interpreter version 5.3
 Lua is a powerful, light-weight programming language designed for extending
 applications.  The language engine is accessible as a library, having a C
 API which allows the application to exchange data with Lua programs and also
 to extend Lua with C functions.  Lua is also used as a general-purpose,
 stand-alone language through the simple command line interpreter provided.
 .
 This package contains runtime libraries.  You shouldn't need to install it
 explicitly.
```

**Comment by jcorporation** [comment] 2020-07-16 17:50
Duplicate of #299 and #300. Is already fixed in devel. I should really release 6.5.2 with this fix.

**Closed by jcorporation** 2020-07-16 17:50 UTC
Labels: bug, duplicate
