### ISSUE TITLE
Version 6.8.1: where is the selection of a song from the file system?

### ISSUE THREAD

**Issue by ustraub** [jcorporation/myMPD#374] opened 2020-11-25 21:12 UTC
I cannot find the option to select a song from browsing the file system. If that option has been removed it would make the current version of mympd useless. 

In the old version 5.2.0 this option was present and this was the reason I was using mympd.

**Comment by john-** [comment] 2020-11-25 21:15
With 6.8.1 when I browse the file system there is a "hamburger" icon to the right of the song.   If you select this you get option to add song to queue.

**Comment by ustraub** [comment] 2020-11-25 21:46
I have added a screenshot. I have clicked the Browse button. I cannot see (or perhaps cannot find) the "browse file system" button/icon on this page.

![grafik](https://user-images.githubusercontent.com/46170211/100284749-f6988c80-2f6f-11eb-85ec-e13d3d359aa2.png)

**Comment by Emilot** [comment] 2020-11-25 22:06
What Theme mode do you have?

**Comment by john-** [comment] 2020-11-25 22:10
I think you also reported error that may be similar another one you reported:
https://github.com/jcorporation/myMPD/issues/364
If so that will be fixed in 6.8.2 (or devel now).   After that error is addrssed the file system option will work.

If that is the same problem it is due to older mpd.   If that is the case DB browse will be disabled intentionally.

**Comment by jcorporation** [comment] 2020-11-26 18:17
Right, this is a duplicate of #364
Is already fixed in devel.

**Closed by jcorporation** 2020-11-26 18:17 UTC
Labels: duplicate
