### ISSUE TITLE
New install did not accept existing configuration

### ISSUE THREAD

**Issue by Joulinar** [jcorporation/myMPD#912] opened 2022-12-01 14:16 UTC
myMPD version: mympd (10.1.3-1) via Debian package

**Describe the bug**

first time service start is failing if a config file has been created before. 

```
root@DietPiR5S:~# journalctl -u mympd
-- Journal begins at Thu 2022-12-01 14:58:40 CET, ends at Thu 2022-12-01 15:04:32 CET. --
Dec 01 15:04:32 DietPiR5S systemd[1]: Started myMPD server daemon.
Dec 01 15:04:32 DietPiR5S systemd[1487]: Found pre-existing public StateDirectory= directory /var/lib/mympd, migrating to /var/lib/private/mympd.
Dec 01 15:04:32 DietPiR5S systemd[1487]: Apparently, service previously had DynamicUser= turned off, and has now turned it on.
Dec 01 15:04:32 DietPiR5S systemd[1487]: Found pre-existing public CacheDirectory= directory /var/cache/mympd, migrating to /var/cache/private/mympd.
Dec 01 15:04:32 DietPiR5S systemd[1487]: Apparently, service previously had DynamicUser= turned off, and has now turned it on.
Dec 01 15:04:32 DietPiR5S mympd[1487]: NOTICE   mympd     Cache dir: "/var/cache/mympd"
Dec 01 15:04:32 DietPiR5S mympd[1487]: NOTICE   mympd     Work dir: "/var/lib/mympd"
Dec 01 15:04:32 DietPiR5S mympd[1487]: ERROR    mympd     Config dir: creating "/var/lib/mympd/config" failed
Dec 01 15:04:32 DietPiR5S mympd[1487]: ERROR    mympd     File exists
Dec 01 15:04:32 DietPiR5S mympd[1487]: Exiting erroneous, thank you for using myMPD
Dec 01 15:04:32 DietPiR5S systemd[1]: mympd.service: Main process exited, code=exited, status=1/FAILURE
Dec 01 15:04:32 DietPiR5S systemd[1]: mympd.service: Failed with result 'exit-code'.
```

As well creating a first time configuration is failing because of missing `mympd` user

```
root@DietPiR5S:~# mympd -c
15:02:47 NOTICE   mympd     Cache dir: "/var/cache/mympd"
15:02:47 NOTICE   mympd     Work dir: "/var/lib/mympd" created
15:02:47 ERROR    mympd     Can't get passwd entry for user "mympd"
Exiting erroneous, thank you for using myMPD
```

**To Reproduce**

1. `eval "curl -sSfL 'https://download.opensuse.org/repositories/home:/jcorporation/Debian_11/Release.key' | gpg --dearmor -o /etc/apt/trusted.gpg.d/dietpi-mympd.gpg --yes"`
2. `eval "echo 'deb https://download.opensuse.org/repositories/home:/jcorporation/Debian_11/ /' > /etc/apt/sources.list.d/dietpi-mympd.list"`
3. `apt update && apt install mympd -y`
4. set the `export` value
```
export MYMPD_HTTP_PORT=1333
export MYMPD_SSL=false
export MYMPD_MPD_HOST='/run/mpd/socket'
export MYMPD_LOGLEVEL=4
```
5. `useradd -m -g dietpi mympd`
6. `mympd -c`
7. `systemctl start mympd`

**Expected behavior**

installation should complete without issues, even if a configuration has been created before. This should be possible according to online docs https://jcorporation.github.io/myMPD/configuration/

> You can use mympd -c to create the initial configuration in the /var/lib/mympd/config/ directory.

**Comment by MichaIng** [comment] 2022-12-01 15:24
Okay, let's discuss here then, just for reference:
- https://github.com/MichaIng/DietPi/issues/5936
- https://github.com/MichaIng/DietPi/issues/5919

With [this](https://github.com/jcorporation/myMPD/commit/fcf667c) commit, if systemd is used, the service user is now a dynamic user, and is with a follow-up commit also not pre-created on package install (reasonably, since this breaks the dynamic user usage). `mympd -c` then fails with an error since the user is missing. In combination with `StateDirectory=mympd`, systemd moves `/var/lib/mympd` into a `private` sub directory, links it back and `chown`s it recursively to the dynamic user on service start, automatically, so access is assured, at least.

In order for `mympd -c` to work, one can pre-create the user, which disables the dynamic user. But now systemd does not change the owner of `/var/lib/mympd` (while it still moves it into `private`), so it has no access to `/var/lib/mympd/config`, which is created by `mympd -c` with `root:root 770`, respectively the contained files even with `root:root 600`, so myMPD does not see anything and fails to start.

The only possibility to pre-create the config, AFAIK, now is:
```sh
useradd -rMU -s /bin/false -d /var/lib/mympd mympd
apt install mympd
export MYMPD_...
mympd -c
chown -R mympd /var/lib/mympd/config
systemctl start mympd
```
This works but reduces security since the config directory can now be written to by the service user, and it needs to be/stay like that since the service user itself starts myMPD right from the start and might need to change or add new configs when things change on future releases.

Another regression is, even with pre-created user, that the service user cannot be granted supplementary group permissions, since in most cases (I still failed to find a consistent logic behind it) setting `Group=` in systemd unit overrides those. So something like `usermod -aG mpd mympd` won't grant myMPD write access to MPD dirs/files with `775`/`664` mode.

**Comment by jcorporation** [comment] 2022-12-01 17:48
Ooops, this is all really bad. I will revert the dynamic user commits and restore the old behavior.

**Comment by MichaIng** [comment] 2022-12-01 18:03
Probably @dvzrv has some opinion as well. And probably we can find a way to keep parts by changing the way `mympd -c` works as well, e.g.:
- If `mympd` user does not exist, it could create the config dir as root user. With dynamic user active, it is chowned correctly at service start.
- In terms of security, not sure whether the benefit of starting the service as `mympd` is better than not granting `mympd` read access to the config dir? It's either the one or the other, since of course the user which starts the service must be able to read the configs. Or two users are used, one to start the service and one to fork off after init 😄. Btw, even if world-readable, it is not actually world-readable, since the dir is located in `/var/lib/private`, which is root-readable only. The systemd service sets it up on startup so that the service scope does have access.
- For enabling the benefits of a fixed system user, `mysql -c` could set this up, creating the user and applying `/var/lib/private/mympd` permissions as required.

**Comment by Joulinar** [comment] 2022-12-01 18:15
> mysql -c 

I guess you mean `mympd -c` 😉

**Comment by jcorporation** [comment] 2022-12-01 18:29
> For enabling the benefits of a fixed system user, mympd -c could set this up

I do not want add special handling for systemd.

> If mympd user does not exist, it could create the config dir as root user. With dynamic user active, it is chowned correctly at service start.

Good idea.

**Comment by dvzrv** [comment] 2022-12-01 19:20
> Using a dynamic user inherently means that myMPD has no write access to anything/anywhere without 777/666 mode, breaking e.g. MPD directory access and the possibility to grant it read access to media dirs/files with 750/640 mode and proper group membership.

That is not true though. You can add an override for whichever directory you want with `ReadWritePaths=` (see https://man.archlinux.org/man/systemd.exec.5).

> In order for mympd -c to work, one can pre-create the user, which disables the dynamic user. But now systemd does not change the owner of /var/lib/mympd (while it still moves it into private), so it has no access to /var/lib/mympd/config, which is created by mympd -c with root:root 770, respectively the contained files even with root:root 600, so myMPD does not see anything and fails to start.

A `DynamicUser` setting is not disabled by creating the user. However, if the user and group as specified by `User=` and `Group=`, they will be used instead and no transient user/group are created  (`If a statically allocated user or group of the configured name already exists, it is used and no dynamic user/group is allocated.`).

In regards to the ownership in `StateDirectory`, I'll quote from the above manpage: `Except in case of ConfigurationDirectory=, the innermost specified directories will be owned by the user and group specified in User= and Group=.`

> Another regression is, even with pre-created user, that the service user cannot be granted supplementary group permissions

Have you tried using `SupplementaryGroups=`?

> I will revert the dynamic user commits and restore the old behavior.

@jcorporation please don't. Running `mympd.service` as root is really nothing we should ever go back to.

The issue that @Joulinar describes in the original post is a *packaging problem*, that does not account for the underlying changes. It is not a problem with the service file.
For situations in which files change locations and owners, there's usually a post-install script (not 100% sure about the terminology here in regards to Debian packaging), which takes care of handling transitions.
In this case this would be e.g. the move of files from `/var/lib/mympd` to `/var/lib/private/mympd` (while the service is not running). This is the responsibility of a package maintainer of a distribution.

**Comment by MichaIng** [comment] 2022-12-01 19:43
> That is not true though. You can add an override for whichever directory you want with `ReadWritePaths=`

Nope, this does not add additional permissions, just overrides the systemd-level access limitations via `ProtectSystem=`. The locations added with `ReadWritePaths=` still require permissions for the user on regular owner/mode level, at least if I do not mix it up. But I can test it. However, requiring to edit or override the default systemd unit is at least not very convenient, even if it it works.

> A `DynamicUser` setting is not disabled by creating the user.

Yeah, I mean there is no "dynamic"/transient user used anymore, but a real system user with a fixed UID which you can grant permissions for, add to group etc. But parts of the setup systemd does with this setting are still applied, as stated, that's true.

> Have you tried using `SupplementaryGroups=`?

That is actually a good idea, I didn't try it. But again, this requires a systemd service override, which isn't so convenient.

> In this case this would be e.g. the move of files from `/var/lib/mympd` to `/var/lib/private/mympd` (while the service is not running). This is the responsibility of a package maintainer of a distribution.

This is done automatically by systemd. But the permissions could be adjusted. E.g. if the `mympd` user exists (in which case the `/var/lib/private/mympd` is not automatically `chown`ed to the user by systemd), the `postinst` script could do that. Or it could remove the static user + group to fully enable the transient one.

The little downside still is that the transient user has full access to the config dir, which was previously explicitly not wanted. It could be adjusted to have read access only, though, and write access to `states` only. But for consistency, and to not have different behaviour and config dir setup depending on init system, the other service files would at best need to be aligned, to start as well as `mympd` user, just as static one, of course.

**Comment by dvzrv** [comment] 2022-12-01 20:53
> myMPD should run out of the box. The user should not need to edit the service unit file to enable a specific myMPD feature.

I can only speak from my perspective here, but the mympd service "just works" (for what I do with it).

> myMPD must access the mpd music directory readonly to provide some functions.

Maybe I'm missing something here, but why does the mympd service need access to another user's files? Isn't that what the mpd service exposes itself for?
The mpd service could be run as any other user (also with per-user music library locations), as a systemd user service. The location of the files may be anywhere on the system. I don't think it is at all advisable to have a service which by default exposes itself on privileged ports over the network (mympd) to have access to *all files* on one's system.

What are the extra functionalities that are described here? From looking at the settings of mympd it seems that it has something to do with lyrics and albumart (but albumart is shown - is that because it is embedded in the files?).

**Comment by dvzrv** [comment] 2022-12-01 20:58
> the transient user has full access to the config dir, which was previously explicitly not wanted.

I was not aware of this.
Looking at the directory structure I am wondering though, why the configuration is located in the state directory (i.e. `/var/lib/mympd/config`) and not in the default configuration location (i.e. `/etc/mympd/`).
Shouldn't the configuration be separated from the state?

**Comment by jcorporation** [comment] 2022-12-01 21:10
> What are the extra functionalities that are described here?

Lyrics, booklets and more flexible albumart

**Comment by jcorporation** [comment] 2022-12-01 21:12
> Looking at the directory structure I am wondering though, why the configuration is located in the state directory (i.e. /var/lib/mympd/config) and not in the default configuration location (i.e. /etc/mympd/).
Shouldn't the configuration be separated from the state?

I wanted to keep the myMPD files in one place, but this could be a not so good idea…

**Comment by jcorporation** [comment] 2022-12-02 09:03
> The main question from my side is, how could a config have created before first service start? Currently, mympd -c is not working and a pre-created configuration is not accepted by mympd.

If I understand the systemd behavior correctly: systemd should manage the pre-created config correctly, if no mympd user exists. In this case the only problem is the not working `mympd -c`, this is fixed with commit 053351a.

Or I miss anything?

***

**Access to mpd music_directory:**

` ProtectSystem=full` enforces a read-only of the filesystem. That is fully acceptable for myMPD. Adding a `SupplementaryGroups=` config should be added if the mpd musicdirectory is not world readable.

**Comment by Joulinar** [comment] 2022-12-02 09:05
ah sorry, I have overlooked the commit. Will run some test once version will become available.

**Comment by jcorporation** [comment] 2022-12-02 12:44
> > The little downside still is that the transient user has full access to the config dir

> I am actually unsure if this is a real protection because the underlying directory is owned by mympd. I should check this.

Checked this: this provides no security. If the underlying directory is owned by mympd, the config folder can be moved and recreated with different values.

**Comment by MichaIng** [comment] 2022-12-02 17:03
> the config folder can be moved and recreated with different values.

Wow, I never knew that indeed a user can move/rename a directory it has not any access to, as long as it has write access to the parent directory. Since there is no sensitive content in the config files and/or those are known by the process anyway, I guess read access is irrelevant, right?

**Comment by MichaIng** [comment] 2022-12-02 18:25
@jcorporation 
Could you give me a hint how to test the playlist upload feature, respectively in which use case it is relevant? Currently, with MPD and myMPD on the same host, when I save a playlist via myMPD web interface, it is actually stored by MPD itself, hence myMPD does not require any directory permissions. Communication is done via MPD socket, which is by default world-writable.

**Comment by jcorporation** [comment] 2022-12-02 19:04
> Could you give me a hint how to test the playlist upload feature,

Which playlist upload feature? Playlists are managed through the mpd protocol.

**Comment by MichaIng** [comment] 2022-12-02 19:53
Basically what you mentioned here: https://github.com/MichaIng/DietPi/issues/3382

**Comment by jcorporation** [comment] 2022-12-02 20:04
The webdav feature was removed, since myMPD was migrated to mongoose 7.

**Comment by MichaIng** [comment] 2022-12-02 20:15
Okay, then it should be all fine as it currently is. A supplementary group then only needs to be added if the media/playlists directory is not world-readable, which should be pretty rare. But it may be worth a hint in the docs, e.g. doing something like that:
```sh
mkdir /etc/systemd/system/mympd.service.d
echo -e '[Service]\nSupplementaryGroups=music' > /etc/systemd/system/mympd.service.d/music-group.conf
```
to grant myMPD read access to directories where only the `music` group has read access to.

**Comment by jcorporation** [comment] 2022-12-02 20:48
There is a hint in the myMPD documentation: 1bd5f94e9fb4bdeb122e046ec59eb660feae35f5

If you can confirm that the current devel patches fixes all issues, I can publish a new myMPD release this weekend.

**Comment by MichaIng** [comment] 2022-12-02 21:30
I suggest to provide the info as I did above via override config. Else every package upgrade reverts the change, and it is less transparent and more difficult to revert for admin as well.

And, the `mpd` group does not exist, at least not on Debian, AFAIK not as part of upstream MPD packages either, so it is probably not a good example 😉.

I'll test the devel branch.

**Comment by jcorporation** [comment] 2022-12-02 21:31
Right, your example is better.

**Comment by MichaIng** [comment] 2022-12-02 21:49
Works great, here is how we do now:
```console
[  OK  ] DietPi-Software | APT install for: /root/mympd_10.1.4-1_amd64.deb
[  OK  ] export MYMPD_LOGLEVEL=4 MYMPD_MPD_HOST=/run/mpd/socket MYMPD_HTTP_PORT=1332 MYMPD_SSL_PORT=1333
[  OK  ] DietPi-Software | systemctl stop mympd
[  OK  ] DietPi-Software | umask 0077
[  OK  ] DietPi-Software | mympd -c
[  OK  ] DietPi-Software | mkdir /var/lib/mympd/state
[  OK  ] DietPi-Software | eval echo '/mnt/dietpi_userdata/Music' > /var/lib/mympd/state/playlist_directory
[  OK  ] DietPi-Software | eval echo '/mnt/dietpi_userdata/Music' > /var/lib/mympd/state/music_directory
[  OK  ] DietPi-Software | umask 0022
root@VM-Bullseye:~# l /var/lib/mympd/
total 32K
drwxrwx--- 2 61876 61876 4.0K Dec  2 22:43 config
drwxrwx--- 2 61876 61876 4.0K Dec  2 22:43 empty
drwxrwx--- 4 61876 61876 4.0K Dec  2 22:43 pics
drwxrwx--- 2 61876 61876 4.0K Dec  2 22:43 scripts
drwxrwx--- 2 61876 61876 4.0K Dec  2 22:43 smartpls
drwxrwx--- 2 61876 61876 4.0K Dec  2 22:43 ssl
drwx------ 3 61876 61876 4.0K Dec  2 22:43 state
drwxrwx--- 2 61876 61876 4.0K Dec  2 22:43 webradios
root@VM-Bullseye:~# ss -tlpn
State          Recv-Q         Send-Q                  Local Address:Port                   Peer Address:Port         Process
LISTEN         0              3                             0.0.0.0:1332                        0.0.0.0:*             users:(("mympd",pid=20222,fd=4))
LISTEN         0              3                             0.0.0.0:1333                        0.0.0.0:*             users:(("mympd",pid=20222,fd=5))
LISTEN         0              5                           127.0.0.1:6600                        0.0.0.0:*             users:(("mpd",pid=20209,fd=10))
LISTEN         0              5                               [::1]:6600                           [::]:*             users:(("mpd",pid=20209,fd=9))
```

**Closed** 2022-12-03 08:32 UTC
Labels: bug
