### ISSUE TITLE
Behaviour in songdetails

### ISSUE THREAD

**Issue by Hajuskin** [jcorporation/myMPD#649] opened 2021-12-23 17:44 UTC
myMPD version: 9.0.2

**Describe the bug**

- Clicking on the date of a song in the songdetails tab opens the search with a filter for every digit of the date:
![chrome_k8TLWr2J70](https://user-images.githubusercontent.com/51139914/147274375-de4126a0-3c52-41bc-ad86-5b945063dbc5.jpg)

- Clicking on the artist name in the songdetails tab does nothing while clicking on the artist name in the songdetails popup opens the search as expected.

**Comment by jcorporation** [comment] 2021-12-23 19:37
This was a regression caused by the improved support. Is fixed in devel.

**Closed by jcorporation** 2021-12-23 19:37 UTC
Labels: bug
