### ISSUE TITLE
Devel build crashes somtimes with the error message "Number too large: 0:..."

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#121] opened 2019-05-21 04:16 UTC
[mympd.conf.txt](https://github.com/jcorporation/myMPD/files/3200763/mympd.conf.txt)

[log1.txt](https://github.com/jcorporation/myMPD/files/3200761/log1.txt)

**Comment by jcorporation** [comment] 2019-05-23 20:32
Uh oh, it seems the max_elements_per_page variable is sometimes not initialized. At the moment I can't reproduce this bug and I see no root cause in your logs.

**Comment by jcorporation** [comment] 2019-05-23 21:32
I think I found the bug, is fixed in devel.

**Closed** 2019-05-23 22:22 UTC
Labels: bug, devel
