### ISSUE TITLE
ver 9.3.1 scroll (touch) does not work on android Chrome/Edge 

### ISSUE THREAD

**Issue by jacgl** [jcorporation/myMPD#759] opened 2022-05-14 15:14 UTC
myMPD version: 9.3.1

Browse/Queue sections: not able to scroll the list scince version 9.3.1 on Android versions of Chrome/Edge (touch interface). However, scrolll is working on Windows for both mouse/touch.

**Comment by jcorporation** [comment] 2022-05-15 08:54
Issue is new for 9.3.x versions?

Please test to enable the enforce mobile view in settings and reload the site.

See you a scale ratio setting in the appearance tab?

**Comment by jacgl** [comment] 2022-05-15 10:28
> Issue is new for 9.3.x versions?
Yes, it is new. I update the container quite regularly. Last update like 2 days ago.

> Please test to enable the enforce mobile view in settings and reload the site.
no impact
in fact, mobile view is always activated on android, independent on this setting

> See you a scale ratio setting in the appearance tab?
Yes, it is visible in the setting menu.
Anyway, I didn't notice any impact on appearance when changed 1.0->0.9->1.0

**Comment by jcorporation** [comment] 2022-05-15 11:04
> Anyway, I didn't notice any impact on appearance when changed 1.0->0.9->1.0

This is a bug in 9.3.1 and should be already fixed in devel.

**Comment by jcorporation** [comment] 2022-05-15 11:56
I could not reproduce this issue. However devel fixes some mobile view issues can you test with devel?

**Comment by jacgl** [comment] 2022-05-15 12:23
> I could not reproduce this issue. However devel fixes some mobile view issues can you test with devel?

Great! It is back working in 9.3.2. Thanks!

**Closed** 2022-05-15 12:27 UTC
Labels: bug
