### ISSUE TITLE
Search filter fields are not shown on mobile browsers

### ISSUE THREAD

**Issue by stefanroellin** [jcorporation/myMPD#673] opened 2022-02-03 13:12 UTC
myMPD version: 9.1.0

If I open myMPD in Chrome on an Android device, the filter fields 'Genre', 'Country' and  'Language' aren't populated. However, if I use Chrome on Ubuntu 21.10, these fields are populated and can be selected.

**Steps to reproduce the behavior:**
1. Go to WebradioDB
2. Click on filter
3. Select country dropdown
4. dropdown is empty

**Expected behavior**

I would expect that the country list is not empty while clicking on it.

**Server plattform:**
 - MPD version: 0.21.4

**Client plattform:**
 - OS: Android
 - Browser: chrome

Same behaviour observed with Samsung Internet Browser.

**Comment by tsunulukai** [comment] 2022-02-03 14:57
I have the same issue in Chrome on Android, but it works fine using Firefox Nightly on Android

Chrome:
![Screenshot_20220203-155405](https://user-images.githubusercontent.com/4215150/152367700-77b46b0e-3e9e-4347-94ba-cfdb2f0dfcd5.jpg)

FireFox Nightly:
![Screenshot_20220203-155506](https://user-images.githubusercontent.com/4215150/152367735-55369c48-1f29-49f3-b981-bd323e67e82e.jpg)

**Comment by jcorporation** [comment] 2022-02-03 17:18
Seems to be a browser incompatibility with custom elements. Is the picture select e.g. for homeicons working? I have no android device to debug…

**Comment by stefanroellin** [comment] 2022-02-03 19:09
Yes, the picture select is working (there is one option "Ligatur benutzen"):

![image](https://user-images.githubusercontent.com/9341235/152411600-69b7d63c-6ec7-4107-b7c2-f8aa4aec8181.png)

Using the developer tools, one can see that the values are populated, but not shown:

![image](https://user-images.githubusercontent.com/9341235/152411793-0d9ac55b-ca62-4a53-9539-b43e527b0ac1.png)

**Comment by jcorporation** [comment] 2022-02-03 19:24
Looking closer to your provided screenshots shows an invalid first option tag (incomplete value tag). Eventually this is the problem.

**Comment by jcorporation** [comment] 2022-02-04 17:26
I can reproduce this issue with safari on my iPhone.

**Comment by jcorporation** [comment] 2022-02-04 20:46
Should now fixed in devel. Can you give it a try and report back?

**Comment by stefanroellin** [comment] 2022-02-05 10:26
I can confirm that the list is now also populated on a mobile browser and it is possible to select e.g. a country to filter the list.

However, the search field in the dropdown doesn't work anymore, neither on a desktop browser nor on a mobile browser.

On a desktop - 9.1.0:
![image](https://user-images.githubusercontent.com/9341235/152638214-1a106abe-d988-40f6-970b-23e203562b4c.png)

On a desktop - current devel version:
![image](https://user-images.githubusercontent.com/9341235/152638277-3fbba2d7-9fed-46fe-8c6f-b514e2c38a72.png)

**Comment by jcorporation** [comment] 2022-02-05 16:45
Filtering the result should now work.

**Comment by stefanroellin** [comment] 2022-02-06 10:35
The filtering now does work - thanks!

However I realized that a recent change has broken "Ligatur":

![image](https://user-images.githubusercontent.com/9341235/152676879-ea6f88ae-a0d8-436f-b1ba-188bee6ccfb1.png)

**Comment by jcorporation** [comment] 2022-02-06 11:31
Should now also be fixed.

**Comment by stefanroellin** [comment] 2022-02-06 13:38
Thanks for the fix.

Unfortunately since commit 39bda25205b8d625b08d1a573d595740bdfb7871 adding a webradio is partially broken, namely the icon isn't added anymore, even if it is added from the favourites:

![image](https://user-images.githubusercontent.com/9341235/152683526-8fef4652-d45b-444a-b7e6-a0bfb55cbec2.png)

and the resulting item on the Homepage:

![image](https://user-images.githubusercontent.com/9341235/152683539-e205167a-68b1-4217-8533-0727ebbf4b18.png)

**Comment by jcorporation** [comment] 2022-02-06 17:02
We can handle this in this issue, it seems to be a regression...

**Comment by jcorporation** [comment] 2022-02-06 17:31
Should work now again.

**Comment by stefanroellin** [comment] 2022-02-06 18:42
Now works again - thanks!

**Closed** 2022-02-06 19:01 UTC
Labels: bug
